<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.7.32">

  <title>quarto-inputecd316496232f7f</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-988e8b3a709629e028e858dec964560e.css">
  <link rel="stylesheet" href="styles.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#000F46" class="quarto-title-block center">
  <h1 class="title"><div class="tight-title">
<div>
ECOM30004/90004
</div>
<div>
Time Series Analysis and Forecasting
</div>
<div class="spacer">

</div>
<div class="bold">
Tutorial 7
</div>
<div class="spacer">

</div>
<div class="author">
Tutor: Pengyun (Kevin) Chen
</div>
<div class="author">
University of Melbourne
</div>
<div class="author">
Semester 2, 2026
</div>
</div></h1>

<div class="quarto-title-authors">
</div>

</section>
<section id="notice" class="slide level2">
<h2>Notice</h2>
<div title="Conditions of Use">
<div class="callout callout-warning callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Conditions of Use</strong></p>
</div>
<div class="callout-content">
<ul>
<li>This document is intended for personal use and is NOT meant to be shared on the internet (e.g.&nbsp;Studocu, ThinkSwap, StudentVIP, Coursehero, etc.)</li>
<li>Do not share this document with anyone, even if they are enrolled in ECOM30004/90004.</li>
<li>Official course materials, such as lecture slides, tutorial sheets and prescribed readings should always be your primary point of reference.</li>
</ul>
</div>
</div>
</div>
</div>
<div style="height: 0.2em;">

</div>
<ul>
<li>Slides accessible here: <code>pengyunc.github.io/TSAF_Week7</code></li>
<li>Download HTML versions here: <a href="https://www.dropbox.com/scl/fo/aoxoud5ex0j42hsrod3dg/ADblAt_jJ9hpESZME9FDcWc?rlkey=0s0oyf1y3uokzvlhbzxe2yy3g&amp;st=kx2yupzr&amp;dl=0">Dropbox Link</a></li>
<li><blue>My consultations for Weeks 7 and 8:</blue> <span class="math display">\[\boxed{\;\textsf{Wednesday 3pm-4pm, FBE 455}\;}\]</span></li>
</ul>
</section>
<section id="recap-of-tutorial-6" class="slide level2">
<h2>Recap of Tutorial 6</h2>
<p><blue>In Tutorial 6, the ADF test indicated that the <span class="math inline">\(\log(CPI_{t})\)</span> series contains a unit root. </blue></p>
<ul>
<li class="fragment"><p>This means we cannot just remove the trend and fit an ARMA model.</p>
<ul>
<li class="fragment"><teal><span class="math inline">\(\to\)</span> We need to first difference the <span class="math inline">\(\log(CPI_{t})\)</span> series to render it stationary.</teal></li>
</ul></li>
<li class="fragment"><p>We then ran the ADF test with drift on <span class="math inline">\(\Delta\log(CPI_{t})\)</span> and the null hypothesis of a unit root was rejected at 5% level.</p>
<ul>
<li class="fragment"><oblue><span class="math inline">\(\to\)</span> <span class="math inline">\(\Delta\log(CPI_{t})\)</span> can be modeled as an ARMA process.</oblue></li>
<li class="fragment">So we proceeded with selecting the optimal ARMA(<span class="math inline">\(p,q\)</span>) order for <span class="math inline">\(\Delta\log(CPI_{t})\)</span> using a grid search of <span class="math inline">\(p=0,\dots,4\)</span> and <span class="math inline">\(q=0,\dots,4\)</span>.</li>
</ul></li>
<li class="fragment"><p><blue><strong>So what is the purpose of ADF test here?</strong></blue></p>
<ul>
<li class="fragment"><p>To assist with selecting <span class="math inline">\(d=0\)</span> or <span class="math inline">\(d=1\)</span> in an ARIMA model.</p></li>
<li class="fragment"><p>We may wonder: Can we let an information criterion (AIC or AICc) select <span class="math inline">\(d\)</span> automatically, alongside <span class="math inline">\(p\)</span> and <span class="math inline">\(q\)</span>?</p></li>
</ul></li>
<li class="fragment"><p><blue><strong>This tutorial:</strong> Maybe we can replace that decision with AIC, just like we pick <span class="math inline">\(p\)</span> and <span class="math inline">\(q\)</span>?</blue> <green><span class="math inline">\(\to\)</span> we will examine this idea with a simulation</green></p></li>
</ul>
</section>
<section id="this-tutorial" class="slide level2 scrollable" data-auto-animate="true">
<h2 data-id="quarto-animate-title">This tutorial</h2>
<p><blue>In this tutorial we will use simulation to explore the possible usefulness of the AIC for deciding whether to difference a time series or not, in comparison to the conventional ADF tests.</blue></p>
<div style="height: 0.2em;">

</div>
<div title="Simulation Setting">
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Simulation Setting</strong></p>
</div>
<div class="callout-content">
<ul>
<li class="fragment"><p>Use a sample size of <span class="math inline">\(n=100\)</span>.</p></li>
<li class="fragment"><p>Fit an AR model with fixed order <span class="math inline">\(p=2\)</span> and with intercept only: <span class="math display">\[\mathrm{ARIMA}(2,0,0):\qquad Y_{t}=\beta_{0}+\phi_{1}Y_{t-1}+\phi_{2}Y_{t-2}+U_{t}\]</span></p></li>
<li class="fragment"><p>A restricted version of this model is to take a first difference of <span class="math inline">\(Y_{t}\)</span>: <span class="math display">\[\mathrm{ARIMA}(1,1,0):\qquad\Delta Y_{t}=\beta_{0}+\psi_{1}\Delta Y_{t-1}+U_{t}\]</span></p></li>
<li class="fragment"><p><blue>Selection Criteria: </blue>Select ARIMA(1,1,0) if <span class="math inline">\(\operatorname{AIC}_{\operatorname{ARIMA(1,1,0)}}&lt;\operatorname{AIC}_{\operatorname{ARIMA(2,0,0)}}\)</span>.</p></li>
<li class="fragment"><p>We will compare the ADF and AIC approaches in two ways:</p>
<ol type="i">
<li class="fragment">proportion of “correct” choice of differencing</li>
<li class="fragment">resulting one-step-ahead forecasting performance.</li>
</ol></li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section id="simulation-data-generating-process" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Simulation: Data Generating Process</h2>
<div title="Data Generating Process">
<div class="callout callout-note callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Data Generating Process</strong></p>
</div>
<div class="callout-content">
<p>The data generating process for the simulation will be</p>
<p><span class="math display">\[Y_{t}=\phi Y_{t-1}+U_{t},\qquad U_{t}\sim\text{i.i.d. N}(0,1)\]</span> with <span class="math inline">\(n=100\)</span> and <span class="math inline">\(\phi_{1}=1,0.95,0.9,0.85,0.8,0.7,0.6,0.5\)</span>.</p>
</div>
</div>
</div>
</div>
<div style="height: 0.5em;">

</div>
<ul>
<li><p>For setting up the code, we select <span class="math inline">\(\phi=0.9\)</span> (without loss of generality), but we can change it later.</p></li>
<li><p>The true underlying process is actually AR(1), although we will fit AR(2).</p></li>
<li><p>When <span class="math inline">\(\phi_{1}\ne 1\)</span>, no differencing is needed for <span class="math inline">\(Y_{t}\)</span> <teal><span class="math inline">\(\to\)</span> the correct choice is AR(2)</teal></p></li>
<li><p>When <span class="math inline">\(\phi_{1}=1\)</span>, <span class="math inline">\(Y_{t}\)</span> is a unit-root process <purple><span class="math inline">\(\to\)</span> the correct choice is ARIMA(1,1,0)</purple></p></li>
</ul>
</section>
<section id="initialisation" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Initialisation</h2>
<p>Load libraries:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">library</span>(forecast)</span>
<span id="cb1-2"><a></a><span class="fu">library</span>(urca)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="height: 0.5em;">

</div>
<p>Set parameters:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a></a>n <span class="ot">&lt;-</span> <span class="dv">100</span>        <span class="co"># Sample size</span></span>
<span id="cb2-2"><a></a>phi1 <span class="ot">&lt;-</span> <span class="fl">0.9</span>     <span class="co"># True value of phi1</span></span>
<span id="cb2-3"><a></a>p <span class="ot">&lt;-</span> <span class="dv">2</span>          <span class="co"># Lag length of AR model</span></span>
<span id="cb2-4"><a></a>t <span class="ot">&lt;-</span> (p<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>n    </span>
<span id="cb2-5"><a></a></span>
<span id="cb2-6"><a></a>reps <span class="ot">&lt;-</span> <span class="dv">1000</span>    <span class="co"># Number of repetitions</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="height: 0.5em;">

</div>
<p>Initialise Container Matrices:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="co"># For storing model selection outcomes by ADF and AIC</span></span>
<span id="cb3-2"><a></a>ur <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">nrow=</span>reps, <span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb3-3"><a></a><span class="fu">colnames</span>(ur) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ADF"</span>, <span class="st">"AIC"</span>)</span>
<span id="cb3-4"><a></a></span>
<span id="cb3-5"><a></a><span class="co"># Matrix of forecast errors for each replication</span></span>
<span id="cb3-6"><a></a>ForecastErrors <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">nrow=</span>reps, <span class="at">ncol=</span><span class="dv">4</span>)</span>
<span id="cb3-7"><a></a><span class="fu">colnames</span>(ForecastErrors) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ARIMA110"</span>, <span class="st">"ARIMA200"</span>, <span class="st">"ADF"</span>, <span class="st">"AIC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="initialisation-1" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Initialisation</h2>
<p>Initialise Container Matrices:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a></a><span class="co"># For storing model selection outcomes by ADF and AIC</span></span>
<span id="cb4-2"><a></a>ur <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">nrow=</span>reps, <span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb4-3"><a></a><span class="fu">colnames</span>(ur) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ADF"</span>, <span class="st">"AIC"</span>)</span>
<span id="cb4-4"><a></a></span>
<span id="cb4-5"><a></a><span class="co"># Matrix of forecast errors for each replication</span></span>
<span id="cb4-6"><a></a>ForecastErrors <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">nrow=</span>reps, <span class="at">ncol=</span><span class="dv">4</span>)</span>
<span id="cb4-7"><a></a><span class="fu">colnames</span>(ForecastErrors) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ARIMA110"</span>, <span class="st">"ARIMA200"</span>, <span class="st">"ADF"</span>, <span class="st">"AIC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="horizontal-line">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">print</span>(ur)        <span class="co"># This should be a matrix of 0's and 1's</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        ADF AIC
   [1,]  NA  NA
   [2,]  NA  NA
   [3,]  NA  NA
   [4,]  NA  NA
   [5,]  NA  NA
   [6,]  NA  NA
   [7,]  NA  NA
   [8,]  NA  NA
   [9,]  NA  NA
  [10,]  NA  NA
  [11,]  NA  NA
  [12,]  NA  NA
  [13,]  NA  NA
  [14,]  NA  NA
  [15,]  NA  NA
  [16,]  NA  NA
  [17,]  NA  NA
  [18,]  NA  NA
  [19,]  NA  NA
  [20,]  NA  NA
  [21,]  NA  NA
  [22,]  NA  NA
  [23,]  NA  NA
  [24,]  NA  NA
  [25,]  NA  NA
  [26,]  NA  NA
  [27,]  NA  NA
  [28,]  NA  NA
  [29,]  NA  NA
  [30,]  NA  NA
  [31,]  NA  NA
  [32,]  NA  NA
  [33,]  NA  NA
  [34,]  NA  NA
  [35,]  NA  NA
  [36,]  NA  NA
  [37,]  NA  NA
  [38,]  NA  NA
  [39,]  NA  NA
  [40,]  NA  NA
  [41,]  NA  NA
  [42,]  NA  NA
  [43,]  NA  NA
  [44,]  NA  NA
  [45,]  NA  NA
  [46,]  NA  NA
  [47,]  NA  NA
  [48,]  NA  NA
  [49,]  NA  NA
  [50,]  NA  NA
  [51,]  NA  NA
  [52,]  NA  NA
  [53,]  NA  NA
  [54,]  NA  NA
  [55,]  NA  NA
  [56,]  NA  NA
  [57,]  NA  NA
  [58,]  NA  NA
  [59,]  NA  NA
  [60,]  NA  NA
  [61,]  NA  NA
  [62,]  NA  NA
  [63,]  NA  NA
  [64,]  NA  NA
  [65,]  NA  NA
  [66,]  NA  NA
  [67,]  NA  NA
  [68,]  NA  NA
  [69,]  NA  NA
  [70,]  NA  NA
  [71,]  NA  NA
  [72,]  NA  NA
  [73,]  NA  NA
  [74,]  NA  NA
  [75,]  NA  NA
  [76,]  NA  NA
  [77,]  NA  NA
  [78,]  NA  NA
  [79,]  NA  NA
  [80,]  NA  NA
  [81,]  NA  NA
  [82,]  NA  NA
  [83,]  NA  NA
  [84,]  NA  NA
  [85,]  NA  NA
  [86,]  NA  NA
  [87,]  NA  NA
  [88,]  NA  NA
  [89,]  NA  NA
  [90,]  NA  NA
  [91,]  NA  NA
  [92,]  NA  NA
  [93,]  NA  NA
  [94,]  NA  NA
  [95,]  NA  NA
  [96,]  NA  NA
  [97,]  NA  NA
  [98,]  NA  NA
  [99,]  NA  NA
 [100,]  NA  NA
 [101,]  NA  NA
 [102,]  NA  NA
 [103,]  NA  NA
 [104,]  NA  NA
 [105,]  NA  NA
 [106,]  NA  NA
 [107,]  NA  NA
 [108,]  NA  NA
 [109,]  NA  NA
 [110,]  NA  NA
 [111,]  NA  NA
 [112,]  NA  NA
 [113,]  NA  NA
 [114,]  NA  NA
 [115,]  NA  NA
 [116,]  NA  NA
 [117,]  NA  NA
 [118,]  NA  NA
 [119,]  NA  NA
 [120,]  NA  NA
 [121,]  NA  NA
 [122,]  NA  NA
 [123,]  NA  NA
 [124,]  NA  NA
 [125,]  NA  NA
 [126,]  NA  NA
 [127,]  NA  NA
 [128,]  NA  NA
 [129,]  NA  NA
 [130,]  NA  NA
 [131,]  NA  NA
 [132,]  NA  NA
 [133,]  NA  NA
 [134,]  NA  NA
 [135,]  NA  NA
 [136,]  NA  NA
 [137,]  NA  NA
 [138,]  NA  NA
 [139,]  NA  NA
 [140,]  NA  NA
 [141,]  NA  NA
 [142,]  NA  NA
 [143,]  NA  NA
 [144,]  NA  NA
 [145,]  NA  NA
 [146,]  NA  NA
 [147,]  NA  NA
 [148,]  NA  NA
 [149,]  NA  NA
 [150,]  NA  NA
 [151,]  NA  NA
 [152,]  NA  NA
 [153,]  NA  NA
 [154,]  NA  NA
 [155,]  NA  NA
 [156,]  NA  NA
 [157,]  NA  NA
 [158,]  NA  NA
 [159,]  NA  NA
 [160,]  NA  NA
 [161,]  NA  NA
 [162,]  NA  NA
 [163,]  NA  NA
 [164,]  NA  NA
 [165,]  NA  NA
 [166,]  NA  NA
 [167,]  NA  NA
 [168,]  NA  NA
 [169,]  NA  NA
 [170,]  NA  NA
 [171,]  NA  NA
 [172,]  NA  NA
 [173,]  NA  NA
 [174,]  NA  NA
 [175,]  NA  NA
 [176,]  NA  NA
 [177,]  NA  NA
 [178,]  NA  NA
 [179,]  NA  NA
 [180,]  NA  NA
 [181,]  NA  NA
 [182,]  NA  NA
 [183,]  NA  NA
 [184,]  NA  NA
 [185,]  NA  NA
 [186,]  NA  NA
 [187,]  NA  NA
 [188,]  NA  NA
 [189,]  NA  NA
 [190,]  NA  NA
 [191,]  NA  NA
 [192,]  NA  NA
 [193,]  NA  NA
 [194,]  NA  NA
 [195,]  NA  NA
 [196,]  NA  NA
 [197,]  NA  NA
 [198,]  NA  NA
 [199,]  NA  NA
 [200,]  NA  NA
 [201,]  NA  NA
 [202,]  NA  NA
 [203,]  NA  NA
 [204,]  NA  NA
 [205,]  NA  NA
 [206,]  NA  NA
 [207,]  NA  NA
 [208,]  NA  NA
 [209,]  NA  NA
 [210,]  NA  NA
 [211,]  NA  NA
 [212,]  NA  NA
 [213,]  NA  NA
 [214,]  NA  NA
 [215,]  NA  NA
 [216,]  NA  NA
 [217,]  NA  NA
 [218,]  NA  NA
 [219,]  NA  NA
 [220,]  NA  NA
 [221,]  NA  NA
 [222,]  NA  NA
 [223,]  NA  NA
 [224,]  NA  NA
 [225,]  NA  NA
 [226,]  NA  NA
 [227,]  NA  NA
 [228,]  NA  NA
 [229,]  NA  NA
 [230,]  NA  NA
 [231,]  NA  NA
 [232,]  NA  NA
 [233,]  NA  NA
 [234,]  NA  NA
 [235,]  NA  NA
 [236,]  NA  NA
 [237,]  NA  NA
 [238,]  NA  NA
 [239,]  NA  NA
 [240,]  NA  NA
 [241,]  NA  NA
 [242,]  NA  NA
 [243,]  NA  NA
 [244,]  NA  NA
 [245,]  NA  NA
 [246,]  NA  NA
 [247,]  NA  NA
 [248,]  NA  NA
 [249,]  NA  NA
 [250,]  NA  NA
 [251,]  NA  NA
 [252,]  NA  NA
 [253,]  NA  NA
 [254,]  NA  NA
 [255,]  NA  NA
 [256,]  NA  NA
 [257,]  NA  NA
 [258,]  NA  NA
 [259,]  NA  NA
 [260,]  NA  NA
 [261,]  NA  NA
 [262,]  NA  NA
 [263,]  NA  NA
 [264,]  NA  NA
 [265,]  NA  NA
 [266,]  NA  NA
 [267,]  NA  NA
 [268,]  NA  NA
 [269,]  NA  NA
 [270,]  NA  NA
 [271,]  NA  NA
 [272,]  NA  NA
 [273,]  NA  NA
 [274,]  NA  NA
 [275,]  NA  NA
 [276,]  NA  NA
 [277,]  NA  NA
 [278,]  NA  NA
 [279,]  NA  NA
 [280,]  NA  NA
 [281,]  NA  NA
 [282,]  NA  NA
 [283,]  NA  NA
 [284,]  NA  NA
 [285,]  NA  NA
 [286,]  NA  NA
 [287,]  NA  NA
 [288,]  NA  NA
 [289,]  NA  NA
 [290,]  NA  NA
 [291,]  NA  NA
 [292,]  NA  NA
 [293,]  NA  NA
 [294,]  NA  NA
 [295,]  NA  NA
 [296,]  NA  NA
 [297,]  NA  NA
 [298,]  NA  NA
 [299,]  NA  NA
 [300,]  NA  NA
 [301,]  NA  NA
 [302,]  NA  NA
 [303,]  NA  NA
 [304,]  NA  NA
 [305,]  NA  NA
 [306,]  NA  NA
 [307,]  NA  NA
 [308,]  NA  NA
 [309,]  NA  NA
 [310,]  NA  NA
 [311,]  NA  NA
 [312,]  NA  NA
 [313,]  NA  NA
 [314,]  NA  NA
 [315,]  NA  NA
 [316,]  NA  NA
 [317,]  NA  NA
 [318,]  NA  NA
 [319,]  NA  NA
 [320,]  NA  NA
 [321,]  NA  NA
 [322,]  NA  NA
 [323,]  NA  NA
 [324,]  NA  NA
 [325,]  NA  NA
 [326,]  NA  NA
 [327,]  NA  NA
 [328,]  NA  NA
 [329,]  NA  NA
 [330,]  NA  NA
 [331,]  NA  NA
 [332,]  NA  NA
 [333,]  NA  NA
 [334,]  NA  NA
 [335,]  NA  NA
 [336,]  NA  NA
 [337,]  NA  NA
 [338,]  NA  NA
 [339,]  NA  NA
 [340,]  NA  NA
 [341,]  NA  NA
 [342,]  NA  NA
 [343,]  NA  NA
 [344,]  NA  NA
 [345,]  NA  NA
 [346,]  NA  NA
 [347,]  NA  NA
 [348,]  NA  NA
 [349,]  NA  NA
 [350,]  NA  NA
 [351,]  NA  NA
 [352,]  NA  NA
 [353,]  NA  NA
 [354,]  NA  NA
 [355,]  NA  NA
 [356,]  NA  NA
 [357,]  NA  NA
 [358,]  NA  NA
 [359,]  NA  NA
 [360,]  NA  NA
 [361,]  NA  NA
 [362,]  NA  NA
 [363,]  NA  NA
 [364,]  NA  NA
 [365,]  NA  NA
 [366,]  NA  NA
 [367,]  NA  NA
 [368,]  NA  NA
 [369,]  NA  NA
 [370,]  NA  NA
 [371,]  NA  NA
 [372,]  NA  NA
 [373,]  NA  NA
 [374,]  NA  NA
 [375,]  NA  NA
 [376,]  NA  NA
 [377,]  NA  NA
 [378,]  NA  NA
 [379,]  NA  NA
 [380,]  NA  NA
 [381,]  NA  NA
 [382,]  NA  NA
 [383,]  NA  NA
 [384,]  NA  NA
 [385,]  NA  NA
 [386,]  NA  NA
 [387,]  NA  NA
 [388,]  NA  NA
 [389,]  NA  NA
 [390,]  NA  NA
 [391,]  NA  NA
 [392,]  NA  NA
 [393,]  NA  NA
 [394,]  NA  NA
 [395,]  NA  NA
 [396,]  NA  NA
 [397,]  NA  NA
 [398,]  NA  NA
 [399,]  NA  NA
 [400,]  NA  NA
 [401,]  NA  NA
 [402,]  NA  NA
 [403,]  NA  NA
 [404,]  NA  NA
 [405,]  NA  NA
 [406,]  NA  NA
 [407,]  NA  NA
 [408,]  NA  NA
 [409,]  NA  NA
 [410,]  NA  NA
 [411,]  NA  NA
 [412,]  NA  NA
 [413,]  NA  NA
 [414,]  NA  NA
 [415,]  NA  NA
 [416,]  NA  NA
 [417,]  NA  NA
 [418,]  NA  NA
 [419,]  NA  NA
 [420,]  NA  NA
 [421,]  NA  NA
 [422,]  NA  NA
 [423,]  NA  NA
 [424,]  NA  NA
 [425,]  NA  NA
 [426,]  NA  NA
 [427,]  NA  NA
 [428,]  NA  NA
 [429,]  NA  NA
 [430,]  NA  NA
 [431,]  NA  NA
 [432,]  NA  NA
 [433,]  NA  NA
 [434,]  NA  NA
 [435,]  NA  NA
 [436,]  NA  NA
 [437,]  NA  NA
 [438,]  NA  NA
 [439,]  NA  NA
 [440,]  NA  NA
 [441,]  NA  NA
 [442,]  NA  NA
 [443,]  NA  NA
 [444,]  NA  NA
 [445,]  NA  NA
 [446,]  NA  NA
 [447,]  NA  NA
 [448,]  NA  NA
 [449,]  NA  NA
 [450,]  NA  NA
 [451,]  NA  NA
 [452,]  NA  NA
 [453,]  NA  NA
 [454,]  NA  NA
 [455,]  NA  NA
 [456,]  NA  NA
 [457,]  NA  NA
 [458,]  NA  NA
 [459,]  NA  NA
 [460,]  NA  NA
 [461,]  NA  NA
 [462,]  NA  NA
 [463,]  NA  NA
 [464,]  NA  NA
 [465,]  NA  NA
 [466,]  NA  NA
 [467,]  NA  NA
 [468,]  NA  NA
 [469,]  NA  NA
 [470,]  NA  NA
 [471,]  NA  NA
 [472,]  NA  NA
 [473,]  NA  NA
 [474,]  NA  NA
 [475,]  NA  NA
 [476,]  NA  NA
 [477,]  NA  NA
 [478,]  NA  NA
 [479,]  NA  NA
 [480,]  NA  NA
 [481,]  NA  NA
 [482,]  NA  NA
 [483,]  NA  NA
 [484,]  NA  NA
 [485,]  NA  NA
 [486,]  NA  NA
 [487,]  NA  NA
 [488,]  NA  NA
 [489,]  NA  NA
 [490,]  NA  NA
 [491,]  NA  NA
 [492,]  NA  NA
 [493,]  NA  NA
 [494,]  NA  NA
 [495,]  NA  NA
 [496,]  NA  NA
 [497,]  NA  NA
 [498,]  NA  NA
 [499,]  NA  NA
 [500,]  NA  NA
 [501,]  NA  NA
 [502,]  NA  NA
 [503,]  NA  NA
 [504,]  NA  NA
 [505,]  NA  NA
 [506,]  NA  NA
 [507,]  NA  NA
 [508,]  NA  NA
 [509,]  NA  NA
 [510,]  NA  NA
 [511,]  NA  NA
 [512,]  NA  NA
 [513,]  NA  NA
 [514,]  NA  NA
 [515,]  NA  NA
 [516,]  NA  NA
 [517,]  NA  NA
 [518,]  NA  NA
 [519,]  NA  NA
 [520,]  NA  NA
 [521,]  NA  NA
 [522,]  NA  NA
 [523,]  NA  NA
 [524,]  NA  NA
 [525,]  NA  NA
 [526,]  NA  NA
 [527,]  NA  NA
 [528,]  NA  NA
 [529,]  NA  NA
 [530,]  NA  NA
 [531,]  NA  NA
 [532,]  NA  NA
 [533,]  NA  NA
 [534,]  NA  NA
 [535,]  NA  NA
 [536,]  NA  NA
 [537,]  NA  NA
 [538,]  NA  NA
 [539,]  NA  NA
 [540,]  NA  NA
 [541,]  NA  NA
 [542,]  NA  NA
 [543,]  NA  NA
 [544,]  NA  NA
 [545,]  NA  NA
 [546,]  NA  NA
 [547,]  NA  NA
 [548,]  NA  NA
 [549,]  NA  NA
 [550,]  NA  NA
 [551,]  NA  NA
 [552,]  NA  NA
 [553,]  NA  NA
 [554,]  NA  NA
 [555,]  NA  NA
 [556,]  NA  NA
 [557,]  NA  NA
 [558,]  NA  NA
 [559,]  NA  NA
 [560,]  NA  NA
 [561,]  NA  NA
 [562,]  NA  NA
 [563,]  NA  NA
 [564,]  NA  NA
 [565,]  NA  NA
 [566,]  NA  NA
 [567,]  NA  NA
 [568,]  NA  NA
 [569,]  NA  NA
 [570,]  NA  NA
 [571,]  NA  NA
 [572,]  NA  NA
 [573,]  NA  NA
 [574,]  NA  NA
 [575,]  NA  NA
 [576,]  NA  NA
 [577,]  NA  NA
 [578,]  NA  NA
 [579,]  NA  NA
 [580,]  NA  NA
 [581,]  NA  NA
 [582,]  NA  NA
 [583,]  NA  NA
 [584,]  NA  NA
 [585,]  NA  NA
 [586,]  NA  NA
 [587,]  NA  NA
 [588,]  NA  NA
 [589,]  NA  NA
 [590,]  NA  NA
 [591,]  NA  NA
 [592,]  NA  NA
 [593,]  NA  NA
 [594,]  NA  NA
 [595,]  NA  NA
 [596,]  NA  NA
 [597,]  NA  NA
 [598,]  NA  NA
 [599,]  NA  NA
 [600,]  NA  NA
 [601,]  NA  NA
 [602,]  NA  NA
 [603,]  NA  NA
 [604,]  NA  NA
 [605,]  NA  NA
 [606,]  NA  NA
 [607,]  NA  NA
 [608,]  NA  NA
 [609,]  NA  NA
 [610,]  NA  NA
 [611,]  NA  NA
 [612,]  NA  NA
 [613,]  NA  NA
 [614,]  NA  NA
 [615,]  NA  NA
 [616,]  NA  NA
 [617,]  NA  NA
 [618,]  NA  NA
 [619,]  NA  NA
 [620,]  NA  NA
 [621,]  NA  NA
 [622,]  NA  NA
 [623,]  NA  NA
 [624,]  NA  NA
 [625,]  NA  NA
 [626,]  NA  NA
 [627,]  NA  NA
 [628,]  NA  NA
 [629,]  NA  NA
 [630,]  NA  NA
 [631,]  NA  NA
 [632,]  NA  NA
 [633,]  NA  NA
 [634,]  NA  NA
 [635,]  NA  NA
 [636,]  NA  NA
 [637,]  NA  NA
 [638,]  NA  NA
 [639,]  NA  NA
 [640,]  NA  NA
 [641,]  NA  NA
 [642,]  NA  NA
 [643,]  NA  NA
 [644,]  NA  NA
 [645,]  NA  NA
 [646,]  NA  NA
 [647,]  NA  NA
 [648,]  NA  NA
 [649,]  NA  NA
 [650,]  NA  NA
 [651,]  NA  NA
 [652,]  NA  NA
 [653,]  NA  NA
 [654,]  NA  NA
 [655,]  NA  NA
 [656,]  NA  NA
 [657,]  NA  NA
 [658,]  NA  NA
 [659,]  NA  NA
 [660,]  NA  NA
 [661,]  NA  NA
 [662,]  NA  NA
 [663,]  NA  NA
 [664,]  NA  NA
 [665,]  NA  NA
 [666,]  NA  NA
 [667,]  NA  NA
 [668,]  NA  NA
 [669,]  NA  NA
 [670,]  NA  NA
 [671,]  NA  NA
 [672,]  NA  NA
 [673,]  NA  NA
 [674,]  NA  NA
 [675,]  NA  NA
 [676,]  NA  NA
 [677,]  NA  NA
 [678,]  NA  NA
 [679,]  NA  NA
 [680,]  NA  NA
 [681,]  NA  NA
 [682,]  NA  NA
 [683,]  NA  NA
 [684,]  NA  NA
 [685,]  NA  NA
 [686,]  NA  NA
 [687,]  NA  NA
 [688,]  NA  NA
 [689,]  NA  NA
 [690,]  NA  NA
 [691,]  NA  NA
 [692,]  NA  NA
 [693,]  NA  NA
 [694,]  NA  NA
 [695,]  NA  NA
 [696,]  NA  NA
 [697,]  NA  NA
 [698,]  NA  NA
 [699,]  NA  NA
 [700,]  NA  NA
 [701,]  NA  NA
 [702,]  NA  NA
 [703,]  NA  NA
 [704,]  NA  NA
 [705,]  NA  NA
 [706,]  NA  NA
 [707,]  NA  NA
 [708,]  NA  NA
 [709,]  NA  NA
 [710,]  NA  NA
 [711,]  NA  NA
 [712,]  NA  NA
 [713,]  NA  NA
 [714,]  NA  NA
 [715,]  NA  NA
 [716,]  NA  NA
 [717,]  NA  NA
 [718,]  NA  NA
 [719,]  NA  NA
 [720,]  NA  NA
 [721,]  NA  NA
 [722,]  NA  NA
 [723,]  NA  NA
 [724,]  NA  NA
 [725,]  NA  NA
 [726,]  NA  NA
 [727,]  NA  NA
 [728,]  NA  NA
 [729,]  NA  NA
 [730,]  NA  NA
 [731,]  NA  NA
 [732,]  NA  NA
 [733,]  NA  NA
 [734,]  NA  NA
 [735,]  NA  NA
 [736,]  NA  NA
 [737,]  NA  NA
 [738,]  NA  NA
 [739,]  NA  NA
 [740,]  NA  NA
 [741,]  NA  NA
 [742,]  NA  NA
 [743,]  NA  NA
 [744,]  NA  NA
 [745,]  NA  NA
 [746,]  NA  NA
 [747,]  NA  NA
 [748,]  NA  NA
 [749,]  NA  NA
 [750,]  NA  NA
 [751,]  NA  NA
 [752,]  NA  NA
 [753,]  NA  NA
 [754,]  NA  NA
 [755,]  NA  NA
 [756,]  NA  NA
 [757,]  NA  NA
 [758,]  NA  NA
 [759,]  NA  NA
 [760,]  NA  NA
 [761,]  NA  NA
 [762,]  NA  NA
 [763,]  NA  NA
 [764,]  NA  NA
 [765,]  NA  NA
 [766,]  NA  NA
 [767,]  NA  NA
 [768,]  NA  NA
 [769,]  NA  NA
 [770,]  NA  NA
 [771,]  NA  NA
 [772,]  NA  NA
 [773,]  NA  NA
 [774,]  NA  NA
 [775,]  NA  NA
 [776,]  NA  NA
 [777,]  NA  NA
 [778,]  NA  NA
 [779,]  NA  NA
 [780,]  NA  NA
 [781,]  NA  NA
 [782,]  NA  NA
 [783,]  NA  NA
 [784,]  NA  NA
 [785,]  NA  NA
 [786,]  NA  NA
 [787,]  NA  NA
 [788,]  NA  NA
 [789,]  NA  NA
 [790,]  NA  NA
 [791,]  NA  NA
 [792,]  NA  NA
 [793,]  NA  NA
 [794,]  NA  NA
 [795,]  NA  NA
 [796,]  NA  NA
 [797,]  NA  NA
 [798,]  NA  NA
 [799,]  NA  NA
 [800,]  NA  NA
 [801,]  NA  NA
 [802,]  NA  NA
 [803,]  NA  NA
 [804,]  NA  NA
 [805,]  NA  NA
 [806,]  NA  NA
 [807,]  NA  NA
 [808,]  NA  NA
 [809,]  NA  NA
 [810,]  NA  NA
 [811,]  NA  NA
 [812,]  NA  NA
 [813,]  NA  NA
 [814,]  NA  NA
 [815,]  NA  NA
 [816,]  NA  NA
 [817,]  NA  NA
 [818,]  NA  NA
 [819,]  NA  NA
 [820,]  NA  NA
 [821,]  NA  NA
 [822,]  NA  NA
 [823,]  NA  NA
 [824,]  NA  NA
 [825,]  NA  NA
 [826,]  NA  NA
 [827,]  NA  NA
 [828,]  NA  NA
 [829,]  NA  NA
 [830,]  NA  NA
 [831,]  NA  NA
 [832,]  NA  NA
 [833,]  NA  NA
 [834,]  NA  NA
 [835,]  NA  NA
 [836,]  NA  NA
 [837,]  NA  NA
 [838,]  NA  NA
 [839,]  NA  NA
 [840,]  NA  NA
 [841,]  NA  NA
 [842,]  NA  NA
 [843,]  NA  NA
 [844,]  NA  NA
 [845,]  NA  NA
 [846,]  NA  NA
 [847,]  NA  NA
 [848,]  NA  NA
 [849,]  NA  NA
 [850,]  NA  NA
 [851,]  NA  NA
 [852,]  NA  NA
 [853,]  NA  NA
 [854,]  NA  NA
 [855,]  NA  NA
 [856,]  NA  NA
 [857,]  NA  NA
 [858,]  NA  NA
 [859,]  NA  NA
 [860,]  NA  NA
 [861,]  NA  NA
 [862,]  NA  NA
 [863,]  NA  NA
 [864,]  NA  NA
 [865,]  NA  NA
 [866,]  NA  NA
 [867,]  NA  NA
 [868,]  NA  NA
 [869,]  NA  NA
 [870,]  NA  NA
 [871,]  NA  NA
 [872,]  NA  NA
 [873,]  NA  NA
 [874,]  NA  NA
 [875,]  NA  NA
 [876,]  NA  NA
 [877,]  NA  NA
 [878,]  NA  NA
 [879,]  NA  NA
 [880,]  NA  NA
 [881,]  NA  NA
 [882,]  NA  NA
 [883,]  NA  NA
 [884,]  NA  NA
 [885,]  NA  NA
 [886,]  NA  NA
 [887,]  NA  NA
 [888,]  NA  NA
 [889,]  NA  NA
 [890,]  NA  NA
 [891,]  NA  NA
 [892,]  NA  NA
 [893,]  NA  NA
 [894,]  NA  NA
 [895,]  NA  NA
 [896,]  NA  NA
 [897,]  NA  NA
 [898,]  NA  NA
 [899,]  NA  NA
 [900,]  NA  NA
 [901,]  NA  NA
 [902,]  NA  NA
 [903,]  NA  NA
 [904,]  NA  NA
 [905,]  NA  NA
 [906,]  NA  NA
 [907,]  NA  NA
 [908,]  NA  NA
 [909,]  NA  NA
 [910,]  NA  NA
 [911,]  NA  NA
 [912,]  NA  NA
 [913,]  NA  NA
 [914,]  NA  NA
 [915,]  NA  NA
 [916,]  NA  NA
 [917,]  NA  NA
 [918,]  NA  NA
 [919,]  NA  NA
 [920,]  NA  NA
 [921,]  NA  NA
 [922,]  NA  NA
 [923,]  NA  NA
 [924,]  NA  NA
 [925,]  NA  NA
 [926,]  NA  NA
 [927,]  NA  NA
 [928,]  NA  NA
 [929,]  NA  NA
 [930,]  NA  NA
 [931,]  NA  NA
 [932,]  NA  NA
 [933,]  NA  NA
 [934,]  NA  NA
 [935,]  NA  NA
 [936,]  NA  NA
 [937,]  NA  NA
 [938,]  NA  NA
 [939,]  NA  NA
 [940,]  NA  NA
 [941,]  NA  NA
 [942,]  NA  NA
 [943,]  NA  NA
 [944,]  NA  NA
 [945,]  NA  NA
 [946,]  NA  NA
 [947,]  NA  NA
 [948,]  NA  NA
 [949,]  NA  NA
 [950,]  NA  NA
 [951,]  NA  NA
 [952,]  NA  NA
 [953,]  NA  NA
 [954,]  NA  NA
 [955,]  NA  NA
 [956,]  NA  NA
 [957,]  NA  NA
 [958,]  NA  NA
 [959,]  NA  NA
 [960,]  NA  NA
 [961,]  NA  NA
 [962,]  NA  NA
 [963,]  NA  NA
 [964,]  NA  NA
 [965,]  NA  NA
 [966,]  NA  NA
 [967,]  NA  NA
 [968,]  NA  NA
 [969,]  NA  NA
 [970,]  NA  NA
 [971,]  NA  NA
 [972,]  NA  NA
 [973,]  NA  NA
 [974,]  NA  NA
 [975,]  NA  NA
 [976,]  NA  NA
 [977,]  NA  NA
 [978,]  NA  NA
 [979,]  NA  NA
 [980,]  NA  NA
 [981,]  NA  NA
 [982,]  NA  NA
 [983,]  NA  NA
 [984,]  NA  NA
 [985,]  NA  NA
 [986,]  NA  NA
 [987,]  NA  NA
 [988,]  NA  NA
 [989,]  NA  NA
 [990,]  NA  NA
 [991,]  NA  NA
 [992,]  NA  NA
 [993,]  NA  NA
 [994,]  NA  NA
 [995,]  NA  NA
 [996,]  NA  NA
 [997,]  NA  NA
 [998,]  NA  NA
 [999,]  NA  NA
[1000,]  NA  NA</code></pre>
</div>
</div>
<div class="absolute" style="font-size: 36px;top: 560px; left: 480px; ">
<p><blue>Store model selection results of <code>ADF</code> (Column 1) and <code>AIC</code> (Column 2):</blue></p>
</div>
<div class="absolute" style="font-size: 36px;top: 720px; left: 500px; ">
<p>unit root/differencing chosen <span class="math inline">\(\to\)</span> record <code>1</code></p>
</div>
<div class="absolute" style="font-size: 36px;top: 670px; left: 500px; ">
<p>no differencing chosen <span class="math inline">\(\to\)</span> record <code>0</code></p>
</div>
</section>
<section id="initialisation-2" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Initialisation</h2>
<p>Initialise Container Matrices:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="co"># For storing model selection outcomes by ADF and AIC</span></span>
<span id="cb7-2"><a></a>ur <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">nrow=</span>reps, <span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb7-3"><a></a><span class="fu">colnames</span>(ur) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ADF"</span>, <span class="st">"AIC"</span>)</span>
<span id="cb7-4"><a></a></span>
<span id="cb7-5"><a></a><span class="co"># Matrix of forecast errors for each replication</span></span>
<span id="cb7-6"><a></a>ForecastErrors <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">nrow=</span>reps, <span class="at">ncol=</span><span class="dv">4</span>)</span>
<span id="cb7-7"><a></a><span class="fu">colnames</span>(ForecastErrors) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ARIMA110"</span>, <span class="st">"ARIMA200"</span>, <span class="st">"ADF"</span>, <span class="st">"AIC"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="horizontal-line">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a></a><span class="fu">print</span>(ForecastErrors)      <span class="co"># This should be a matrix of forecast errors</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        ARIMA110 ARIMA200 ADF AIC
   [1,]       NA       NA  NA  NA
   [2,]       NA       NA  NA  NA
   [3,]       NA       NA  NA  NA
   [4,]       NA       NA  NA  NA
   [5,]       NA       NA  NA  NA
   [6,]       NA       NA  NA  NA
   [7,]       NA       NA  NA  NA
   [8,]       NA       NA  NA  NA
   [9,]       NA       NA  NA  NA
  [10,]       NA       NA  NA  NA
  [11,]       NA       NA  NA  NA
  [12,]       NA       NA  NA  NA
  [13,]       NA       NA  NA  NA
  [14,]       NA       NA  NA  NA
  [15,]       NA       NA  NA  NA
  [16,]       NA       NA  NA  NA
  [17,]       NA       NA  NA  NA
  [18,]       NA       NA  NA  NA
  [19,]       NA       NA  NA  NA
  [20,]       NA       NA  NA  NA
  [21,]       NA       NA  NA  NA
  [22,]       NA       NA  NA  NA
  [23,]       NA       NA  NA  NA
  [24,]       NA       NA  NA  NA
  [25,]       NA       NA  NA  NA
  [26,]       NA       NA  NA  NA
  [27,]       NA       NA  NA  NA
  [28,]       NA       NA  NA  NA
  [29,]       NA       NA  NA  NA
  [30,]       NA       NA  NA  NA
  [31,]       NA       NA  NA  NA
  [32,]       NA       NA  NA  NA
  [33,]       NA       NA  NA  NA
  [34,]       NA       NA  NA  NA
  [35,]       NA       NA  NA  NA
  [36,]       NA       NA  NA  NA
  [37,]       NA       NA  NA  NA
  [38,]       NA       NA  NA  NA
  [39,]       NA       NA  NA  NA
  [40,]       NA       NA  NA  NA
  [41,]       NA       NA  NA  NA
  [42,]       NA       NA  NA  NA
  [43,]       NA       NA  NA  NA
  [44,]       NA       NA  NA  NA
  [45,]       NA       NA  NA  NA
  [46,]       NA       NA  NA  NA
  [47,]       NA       NA  NA  NA
  [48,]       NA       NA  NA  NA
  [49,]       NA       NA  NA  NA
  [50,]       NA       NA  NA  NA
  [51,]       NA       NA  NA  NA
  [52,]       NA       NA  NA  NA
  [53,]       NA       NA  NA  NA
  [54,]       NA       NA  NA  NA
  [55,]       NA       NA  NA  NA
  [56,]       NA       NA  NA  NA
  [57,]       NA       NA  NA  NA
  [58,]       NA       NA  NA  NA
  [59,]       NA       NA  NA  NA
  [60,]       NA       NA  NA  NA
  [61,]       NA       NA  NA  NA
  [62,]       NA       NA  NA  NA
  [63,]       NA       NA  NA  NA
  [64,]       NA       NA  NA  NA
  [65,]       NA       NA  NA  NA
  [66,]       NA       NA  NA  NA
  [67,]       NA       NA  NA  NA
  [68,]       NA       NA  NA  NA
  [69,]       NA       NA  NA  NA
  [70,]       NA       NA  NA  NA
  [71,]       NA       NA  NA  NA
  [72,]       NA       NA  NA  NA
  [73,]       NA       NA  NA  NA
  [74,]       NA       NA  NA  NA
  [75,]       NA       NA  NA  NA
  [76,]       NA       NA  NA  NA
  [77,]       NA       NA  NA  NA
  [78,]       NA       NA  NA  NA
  [79,]       NA       NA  NA  NA
  [80,]       NA       NA  NA  NA
  [81,]       NA       NA  NA  NA
  [82,]       NA       NA  NA  NA
  [83,]       NA       NA  NA  NA
  [84,]       NA       NA  NA  NA
  [85,]       NA       NA  NA  NA
  [86,]       NA       NA  NA  NA
  [87,]       NA       NA  NA  NA
  [88,]       NA       NA  NA  NA
  [89,]       NA       NA  NA  NA
  [90,]       NA       NA  NA  NA
  [91,]       NA       NA  NA  NA
  [92,]       NA       NA  NA  NA
  [93,]       NA       NA  NA  NA
  [94,]       NA       NA  NA  NA
  [95,]       NA       NA  NA  NA
  [96,]       NA       NA  NA  NA
  [97,]       NA       NA  NA  NA
  [98,]       NA       NA  NA  NA
  [99,]       NA       NA  NA  NA
 [100,]       NA       NA  NA  NA
 [101,]       NA       NA  NA  NA
 [102,]       NA       NA  NA  NA
 [103,]       NA       NA  NA  NA
 [104,]       NA       NA  NA  NA
 [105,]       NA       NA  NA  NA
 [106,]       NA       NA  NA  NA
 [107,]       NA       NA  NA  NA
 [108,]       NA       NA  NA  NA
 [109,]       NA       NA  NA  NA
 [110,]       NA       NA  NA  NA
 [111,]       NA       NA  NA  NA
 [112,]       NA       NA  NA  NA
 [113,]       NA       NA  NA  NA
 [114,]       NA       NA  NA  NA
 [115,]       NA       NA  NA  NA
 [116,]       NA       NA  NA  NA
 [117,]       NA       NA  NA  NA
 [118,]       NA       NA  NA  NA
 [119,]       NA       NA  NA  NA
 [120,]       NA       NA  NA  NA
 [121,]       NA       NA  NA  NA
 [122,]       NA       NA  NA  NA
 [123,]       NA       NA  NA  NA
 [124,]       NA       NA  NA  NA
 [125,]       NA       NA  NA  NA
 [126,]       NA       NA  NA  NA
 [127,]       NA       NA  NA  NA
 [128,]       NA       NA  NA  NA
 [129,]       NA       NA  NA  NA
 [130,]       NA       NA  NA  NA
 [131,]       NA       NA  NA  NA
 [132,]       NA       NA  NA  NA
 [133,]       NA       NA  NA  NA
 [134,]       NA       NA  NA  NA
 [135,]       NA       NA  NA  NA
 [136,]       NA       NA  NA  NA
 [137,]       NA       NA  NA  NA
 [138,]       NA       NA  NA  NA
 [139,]       NA       NA  NA  NA
 [140,]       NA       NA  NA  NA
 [141,]       NA       NA  NA  NA
 [142,]       NA       NA  NA  NA
 [143,]       NA       NA  NA  NA
 [144,]       NA       NA  NA  NA
 [145,]       NA       NA  NA  NA
 [146,]       NA       NA  NA  NA
 [147,]       NA       NA  NA  NA
 [148,]       NA       NA  NA  NA
 [149,]       NA       NA  NA  NA
 [150,]       NA       NA  NA  NA
 [151,]       NA       NA  NA  NA
 [152,]       NA       NA  NA  NA
 [153,]       NA       NA  NA  NA
 [154,]       NA       NA  NA  NA
 [155,]       NA       NA  NA  NA
 [156,]       NA       NA  NA  NA
 [157,]       NA       NA  NA  NA
 [158,]       NA       NA  NA  NA
 [159,]       NA       NA  NA  NA
 [160,]       NA       NA  NA  NA
 [161,]       NA       NA  NA  NA
 [162,]       NA       NA  NA  NA
 [163,]       NA       NA  NA  NA
 [164,]       NA       NA  NA  NA
 [165,]       NA       NA  NA  NA
 [166,]       NA       NA  NA  NA
 [167,]       NA       NA  NA  NA
 [168,]       NA       NA  NA  NA
 [169,]       NA       NA  NA  NA
 [170,]       NA       NA  NA  NA
 [171,]       NA       NA  NA  NA
 [172,]       NA       NA  NA  NA
 [173,]       NA       NA  NA  NA
 [174,]       NA       NA  NA  NA
 [175,]       NA       NA  NA  NA
 [176,]       NA       NA  NA  NA
 [177,]       NA       NA  NA  NA
 [178,]       NA       NA  NA  NA
 [179,]       NA       NA  NA  NA
 [180,]       NA       NA  NA  NA
 [181,]       NA       NA  NA  NA
 [182,]       NA       NA  NA  NA
 [183,]       NA       NA  NA  NA
 [184,]       NA       NA  NA  NA
 [185,]       NA       NA  NA  NA
 [186,]       NA       NA  NA  NA
 [187,]       NA       NA  NA  NA
 [188,]       NA       NA  NA  NA
 [189,]       NA       NA  NA  NA
 [190,]       NA       NA  NA  NA
 [191,]       NA       NA  NA  NA
 [192,]       NA       NA  NA  NA
 [193,]       NA       NA  NA  NA
 [194,]       NA       NA  NA  NA
 [195,]       NA       NA  NA  NA
 [196,]       NA       NA  NA  NA
 [197,]       NA       NA  NA  NA
 [198,]       NA       NA  NA  NA
 [199,]       NA       NA  NA  NA
 [200,]       NA       NA  NA  NA
 [201,]       NA       NA  NA  NA
 [202,]       NA       NA  NA  NA
 [203,]       NA       NA  NA  NA
 [204,]       NA       NA  NA  NA
 [205,]       NA       NA  NA  NA
 [206,]       NA       NA  NA  NA
 [207,]       NA       NA  NA  NA
 [208,]       NA       NA  NA  NA
 [209,]       NA       NA  NA  NA
 [210,]       NA       NA  NA  NA
 [211,]       NA       NA  NA  NA
 [212,]       NA       NA  NA  NA
 [213,]       NA       NA  NA  NA
 [214,]       NA       NA  NA  NA
 [215,]       NA       NA  NA  NA
 [216,]       NA       NA  NA  NA
 [217,]       NA       NA  NA  NA
 [218,]       NA       NA  NA  NA
 [219,]       NA       NA  NA  NA
 [220,]       NA       NA  NA  NA
 [221,]       NA       NA  NA  NA
 [222,]       NA       NA  NA  NA
 [223,]       NA       NA  NA  NA
 [224,]       NA       NA  NA  NA
 [225,]       NA       NA  NA  NA
 [226,]       NA       NA  NA  NA
 [227,]       NA       NA  NA  NA
 [228,]       NA       NA  NA  NA
 [229,]       NA       NA  NA  NA
 [230,]       NA       NA  NA  NA
 [231,]       NA       NA  NA  NA
 [232,]       NA       NA  NA  NA
 [233,]       NA       NA  NA  NA
 [234,]       NA       NA  NA  NA
 [235,]       NA       NA  NA  NA
 [236,]       NA       NA  NA  NA
 [237,]       NA       NA  NA  NA
 [238,]       NA       NA  NA  NA
 [239,]       NA       NA  NA  NA
 [240,]       NA       NA  NA  NA
 [241,]       NA       NA  NA  NA
 [242,]       NA       NA  NA  NA
 [243,]       NA       NA  NA  NA
 [244,]       NA       NA  NA  NA
 [245,]       NA       NA  NA  NA
 [246,]       NA       NA  NA  NA
 [247,]       NA       NA  NA  NA
 [248,]       NA       NA  NA  NA
 [249,]       NA       NA  NA  NA
 [250,]       NA       NA  NA  NA
 [251,]       NA       NA  NA  NA
 [252,]       NA       NA  NA  NA
 [253,]       NA       NA  NA  NA
 [254,]       NA       NA  NA  NA
 [255,]       NA       NA  NA  NA
 [256,]       NA       NA  NA  NA
 [257,]       NA       NA  NA  NA
 [258,]       NA       NA  NA  NA
 [259,]       NA       NA  NA  NA
 [260,]       NA       NA  NA  NA
 [261,]       NA       NA  NA  NA
 [262,]       NA       NA  NA  NA
 [263,]       NA       NA  NA  NA
 [264,]       NA       NA  NA  NA
 [265,]       NA       NA  NA  NA
 [266,]       NA       NA  NA  NA
 [267,]       NA       NA  NA  NA
 [268,]       NA       NA  NA  NA
 [269,]       NA       NA  NA  NA
 [270,]       NA       NA  NA  NA
 [271,]       NA       NA  NA  NA
 [272,]       NA       NA  NA  NA
 [273,]       NA       NA  NA  NA
 [274,]       NA       NA  NA  NA
 [275,]       NA       NA  NA  NA
 [276,]       NA       NA  NA  NA
 [277,]       NA       NA  NA  NA
 [278,]       NA       NA  NA  NA
 [279,]       NA       NA  NA  NA
 [280,]       NA       NA  NA  NA
 [281,]       NA       NA  NA  NA
 [282,]       NA       NA  NA  NA
 [283,]       NA       NA  NA  NA
 [284,]       NA       NA  NA  NA
 [285,]       NA       NA  NA  NA
 [286,]       NA       NA  NA  NA
 [287,]       NA       NA  NA  NA
 [288,]       NA       NA  NA  NA
 [289,]       NA       NA  NA  NA
 [290,]       NA       NA  NA  NA
 [291,]       NA       NA  NA  NA
 [292,]       NA       NA  NA  NA
 [293,]       NA       NA  NA  NA
 [294,]       NA       NA  NA  NA
 [295,]       NA       NA  NA  NA
 [296,]       NA       NA  NA  NA
 [297,]       NA       NA  NA  NA
 [298,]       NA       NA  NA  NA
 [299,]       NA       NA  NA  NA
 [300,]       NA       NA  NA  NA
 [301,]       NA       NA  NA  NA
 [302,]       NA       NA  NA  NA
 [303,]       NA       NA  NA  NA
 [304,]       NA       NA  NA  NA
 [305,]       NA       NA  NA  NA
 [306,]       NA       NA  NA  NA
 [307,]       NA       NA  NA  NA
 [308,]       NA       NA  NA  NA
 [309,]       NA       NA  NA  NA
 [310,]       NA       NA  NA  NA
 [311,]       NA       NA  NA  NA
 [312,]       NA       NA  NA  NA
 [313,]       NA       NA  NA  NA
 [314,]       NA       NA  NA  NA
 [315,]       NA       NA  NA  NA
 [316,]       NA       NA  NA  NA
 [317,]       NA       NA  NA  NA
 [318,]       NA       NA  NA  NA
 [319,]       NA       NA  NA  NA
 [320,]       NA       NA  NA  NA
 [321,]       NA       NA  NA  NA
 [322,]       NA       NA  NA  NA
 [323,]       NA       NA  NA  NA
 [324,]       NA       NA  NA  NA
 [325,]       NA       NA  NA  NA
 [326,]       NA       NA  NA  NA
 [327,]       NA       NA  NA  NA
 [328,]       NA       NA  NA  NA
 [329,]       NA       NA  NA  NA
 [330,]       NA       NA  NA  NA
 [331,]       NA       NA  NA  NA
 [332,]       NA       NA  NA  NA
 [333,]       NA       NA  NA  NA
 [334,]       NA       NA  NA  NA
 [335,]       NA       NA  NA  NA
 [336,]       NA       NA  NA  NA
 [337,]       NA       NA  NA  NA
 [338,]       NA       NA  NA  NA
 [339,]       NA       NA  NA  NA
 [340,]       NA       NA  NA  NA
 [341,]       NA       NA  NA  NA
 [342,]       NA       NA  NA  NA
 [343,]       NA       NA  NA  NA
 [344,]       NA       NA  NA  NA
 [345,]       NA       NA  NA  NA
 [346,]       NA       NA  NA  NA
 [347,]       NA       NA  NA  NA
 [348,]       NA       NA  NA  NA
 [349,]       NA       NA  NA  NA
 [350,]       NA       NA  NA  NA
 [351,]       NA       NA  NA  NA
 [352,]       NA       NA  NA  NA
 [353,]       NA       NA  NA  NA
 [354,]       NA       NA  NA  NA
 [355,]       NA       NA  NA  NA
 [356,]       NA       NA  NA  NA
 [357,]       NA       NA  NA  NA
 [358,]       NA       NA  NA  NA
 [359,]       NA       NA  NA  NA
 [360,]       NA       NA  NA  NA
 [361,]       NA       NA  NA  NA
 [362,]       NA       NA  NA  NA
 [363,]       NA       NA  NA  NA
 [364,]       NA       NA  NA  NA
 [365,]       NA       NA  NA  NA
 [366,]       NA       NA  NA  NA
 [367,]       NA       NA  NA  NA
 [368,]       NA       NA  NA  NA
 [369,]       NA       NA  NA  NA
 [370,]       NA       NA  NA  NA
 [371,]       NA       NA  NA  NA
 [372,]       NA       NA  NA  NA
 [373,]       NA       NA  NA  NA
 [374,]       NA       NA  NA  NA
 [375,]       NA       NA  NA  NA
 [376,]       NA       NA  NA  NA
 [377,]       NA       NA  NA  NA
 [378,]       NA       NA  NA  NA
 [379,]       NA       NA  NA  NA
 [380,]       NA       NA  NA  NA
 [381,]       NA       NA  NA  NA
 [382,]       NA       NA  NA  NA
 [383,]       NA       NA  NA  NA
 [384,]       NA       NA  NA  NA
 [385,]       NA       NA  NA  NA
 [386,]       NA       NA  NA  NA
 [387,]       NA       NA  NA  NA
 [388,]       NA       NA  NA  NA
 [389,]       NA       NA  NA  NA
 [390,]       NA       NA  NA  NA
 [391,]       NA       NA  NA  NA
 [392,]       NA       NA  NA  NA
 [393,]       NA       NA  NA  NA
 [394,]       NA       NA  NA  NA
 [395,]       NA       NA  NA  NA
 [396,]       NA       NA  NA  NA
 [397,]       NA       NA  NA  NA
 [398,]       NA       NA  NA  NA
 [399,]       NA       NA  NA  NA
 [400,]       NA       NA  NA  NA
 [401,]       NA       NA  NA  NA
 [402,]       NA       NA  NA  NA
 [403,]       NA       NA  NA  NA
 [404,]       NA       NA  NA  NA
 [405,]       NA       NA  NA  NA
 [406,]       NA       NA  NA  NA
 [407,]       NA       NA  NA  NA
 [408,]       NA       NA  NA  NA
 [409,]       NA       NA  NA  NA
 [410,]       NA       NA  NA  NA
 [411,]       NA       NA  NA  NA
 [412,]       NA       NA  NA  NA
 [413,]       NA       NA  NA  NA
 [414,]       NA       NA  NA  NA
 [415,]       NA       NA  NA  NA
 [416,]       NA       NA  NA  NA
 [417,]       NA       NA  NA  NA
 [418,]       NA       NA  NA  NA
 [419,]       NA       NA  NA  NA
 [420,]       NA       NA  NA  NA
 [421,]       NA       NA  NA  NA
 [422,]       NA       NA  NA  NA
 [423,]       NA       NA  NA  NA
 [424,]       NA       NA  NA  NA
 [425,]       NA       NA  NA  NA
 [426,]       NA       NA  NA  NA
 [427,]       NA       NA  NA  NA
 [428,]       NA       NA  NA  NA
 [429,]       NA       NA  NA  NA
 [430,]       NA       NA  NA  NA
 [431,]       NA       NA  NA  NA
 [432,]       NA       NA  NA  NA
 [433,]       NA       NA  NA  NA
 [434,]       NA       NA  NA  NA
 [435,]       NA       NA  NA  NA
 [436,]       NA       NA  NA  NA
 [437,]       NA       NA  NA  NA
 [438,]       NA       NA  NA  NA
 [439,]       NA       NA  NA  NA
 [440,]       NA       NA  NA  NA
 [441,]       NA       NA  NA  NA
 [442,]       NA       NA  NA  NA
 [443,]       NA       NA  NA  NA
 [444,]       NA       NA  NA  NA
 [445,]       NA       NA  NA  NA
 [446,]       NA       NA  NA  NA
 [447,]       NA       NA  NA  NA
 [448,]       NA       NA  NA  NA
 [449,]       NA       NA  NA  NA
 [450,]       NA       NA  NA  NA
 [451,]       NA       NA  NA  NA
 [452,]       NA       NA  NA  NA
 [453,]       NA       NA  NA  NA
 [454,]       NA       NA  NA  NA
 [455,]       NA       NA  NA  NA
 [456,]       NA       NA  NA  NA
 [457,]       NA       NA  NA  NA
 [458,]       NA       NA  NA  NA
 [459,]       NA       NA  NA  NA
 [460,]       NA       NA  NA  NA
 [461,]       NA       NA  NA  NA
 [462,]       NA       NA  NA  NA
 [463,]       NA       NA  NA  NA
 [464,]       NA       NA  NA  NA
 [465,]       NA       NA  NA  NA
 [466,]       NA       NA  NA  NA
 [467,]       NA       NA  NA  NA
 [468,]       NA       NA  NA  NA
 [469,]       NA       NA  NA  NA
 [470,]       NA       NA  NA  NA
 [471,]       NA       NA  NA  NA
 [472,]       NA       NA  NA  NA
 [473,]       NA       NA  NA  NA
 [474,]       NA       NA  NA  NA
 [475,]       NA       NA  NA  NA
 [476,]       NA       NA  NA  NA
 [477,]       NA       NA  NA  NA
 [478,]       NA       NA  NA  NA
 [479,]       NA       NA  NA  NA
 [480,]       NA       NA  NA  NA
 [481,]       NA       NA  NA  NA
 [482,]       NA       NA  NA  NA
 [483,]       NA       NA  NA  NA
 [484,]       NA       NA  NA  NA
 [485,]       NA       NA  NA  NA
 [486,]       NA       NA  NA  NA
 [487,]       NA       NA  NA  NA
 [488,]       NA       NA  NA  NA
 [489,]       NA       NA  NA  NA
 [490,]       NA       NA  NA  NA
 [491,]       NA       NA  NA  NA
 [492,]       NA       NA  NA  NA
 [493,]       NA       NA  NA  NA
 [494,]       NA       NA  NA  NA
 [495,]       NA       NA  NA  NA
 [496,]       NA       NA  NA  NA
 [497,]       NA       NA  NA  NA
 [498,]       NA       NA  NA  NA
 [499,]       NA       NA  NA  NA
 [500,]       NA       NA  NA  NA
 [501,]       NA       NA  NA  NA
 [502,]       NA       NA  NA  NA
 [503,]       NA       NA  NA  NA
 [504,]       NA       NA  NA  NA
 [505,]       NA       NA  NA  NA
 [506,]       NA       NA  NA  NA
 [507,]       NA       NA  NA  NA
 [508,]       NA       NA  NA  NA
 [509,]       NA       NA  NA  NA
 [510,]       NA       NA  NA  NA
 [511,]       NA       NA  NA  NA
 [512,]       NA       NA  NA  NA
 [513,]       NA       NA  NA  NA
 [514,]       NA       NA  NA  NA
 [515,]       NA       NA  NA  NA
 [516,]       NA       NA  NA  NA
 [517,]       NA       NA  NA  NA
 [518,]       NA       NA  NA  NA
 [519,]       NA       NA  NA  NA
 [520,]       NA       NA  NA  NA
 [521,]       NA       NA  NA  NA
 [522,]       NA       NA  NA  NA
 [523,]       NA       NA  NA  NA
 [524,]       NA       NA  NA  NA
 [525,]       NA       NA  NA  NA
 [526,]       NA       NA  NA  NA
 [527,]       NA       NA  NA  NA
 [528,]       NA       NA  NA  NA
 [529,]       NA       NA  NA  NA
 [530,]       NA       NA  NA  NA
 [531,]       NA       NA  NA  NA
 [532,]       NA       NA  NA  NA
 [533,]       NA       NA  NA  NA
 [534,]       NA       NA  NA  NA
 [535,]       NA       NA  NA  NA
 [536,]       NA       NA  NA  NA
 [537,]       NA       NA  NA  NA
 [538,]       NA       NA  NA  NA
 [539,]       NA       NA  NA  NA
 [540,]       NA       NA  NA  NA
 [541,]       NA       NA  NA  NA
 [542,]       NA       NA  NA  NA
 [543,]       NA       NA  NA  NA
 [544,]       NA       NA  NA  NA
 [545,]       NA       NA  NA  NA
 [546,]       NA       NA  NA  NA
 [547,]       NA       NA  NA  NA
 [548,]       NA       NA  NA  NA
 [549,]       NA       NA  NA  NA
 [550,]       NA       NA  NA  NA
 [551,]       NA       NA  NA  NA
 [552,]       NA       NA  NA  NA
 [553,]       NA       NA  NA  NA
 [554,]       NA       NA  NA  NA
 [555,]       NA       NA  NA  NA
 [556,]       NA       NA  NA  NA
 [557,]       NA       NA  NA  NA
 [558,]       NA       NA  NA  NA
 [559,]       NA       NA  NA  NA
 [560,]       NA       NA  NA  NA
 [561,]       NA       NA  NA  NA
 [562,]       NA       NA  NA  NA
 [563,]       NA       NA  NA  NA
 [564,]       NA       NA  NA  NA
 [565,]       NA       NA  NA  NA
 [566,]       NA       NA  NA  NA
 [567,]       NA       NA  NA  NA
 [568,]       NA       NA  NA  NA
 [569,]       NA       NA  NA  NA
 [570,]       NA       NA  NA  NA
 [571,]       NA       NA  NA  NA
 [572,]       NA       NA  NA  NA
 [573,]       NA       NA  NA  NA
 [574,]       NA       NA  NA  NA
 [575,]       NA       NA  NA  NA
 [576,]       NA       NA  NA  NA
 [577,]       NA       NA  NA  NA
 [578,]       NA       NA  NA  NA
 [579,]       NA       NA  NA  NA
 [580,]       NA       NA  NA  NA
 [581,]       NA       NA  NA  NA
 [582,]       NA       NA  NA  NA
 [583,]       NA       NA  NA  NA
 [584,]       NA       NA  NA  NA
 [585,]       NA       NA  NA  NA
 [586,]       NA       NA  NA  NA
 [587,]       NA       NA  NA  NA
 [588,]       NA       NA  NA  NA
 [589,]       NA       NA  NA  NA
 [590,]       NA       NA  NA  NA
 [591,]       NA       NA  NA  NA
 [592,]       NA       NA  NA  NA
 [593,]       NA       NA  NA  NA
 [594,]       NA       NA  NA  NA
 [595,]       NA       NA  NA  NA
 [596,]       NA       NA  NA  NA
 [597,]       NA       NA  NA  NA
 [598,]       NA       NA  NA  NA
 [599,]       NA       NA  NA  NA
 [600,]       NA       NA  NA  NA
 [601,]       NA       NA  NA  NA
 [602,]       NA       NA  NA  NA
 [603,]       NA       NA  NA  NA
 [604,]       NA       NA  NA  NA
 [605,]       NA       NA  NA  NA
 [606,]       NA       NA  NA  NA
 [607,]       NA       NA  NA  NA
 [608,]       NA       NA  NA  NA
 [609,]       NA       NA  NA  NA
 [610,]       NA       NA  NA  NA
 [611,]       NA       NA  NA  NA
 [612,]       NA       NA  NA  NA
 [613,]       NA       NA  NA  NA
 [614,]       NA       NA  NA  NA
 [615,]       NA       NA  NA  NA
 [616,]       NA       NA  NA  NA
 [617,]       NA       NA  NA  NA
 [618,]       NA       NA  NA  NA
 [619,]       NA       NA  NA  NA
 [620,]       NA       NA  NA  NA
 [621,]       NA       NA  NA  NA
 [622,]       NA       NA  NA  NA
 [623,]       NA       NA  NA  NA
 [624,]       NA       NA  NA  NA
 [625,]       NA       NA  NA  NA
 [626,]       NA       NA  NA  NA
 [627,]       NA       NA  NA  NA
 [628,]       NA       NA  NA  NA
 [629,]       NA       NA  NA  NA
 [630,]       NA       NA  NA  NA
 [631,]       NA       NA  NA  NA
 [632,]       NA       NA  NA  NA
 [633,]       NA       NA  NA  NA
 [634,]       NA       NA  NA  NA
 [635,]       NA       NA  NA  NA
 [636,]       NA       NA  NA  NA
 [637,]       NA       NA  NA  NA
 [638,]       NA       NA  NA  NA
 [639,]       NA       NA  NA  NA
 [640,]       NA       NA  NA  NA
 [641,]       NA       NA  NA  NA
 [642,]       NA       NA  NA  NA
 [643,]       NA       NA  NA  NA
 [644,]       NA       NA  NA  NA
 [645,]       NA       NA  NA  NA
 [646,]       NA       NA  NA  NA
 [647,]       NA       NA  NA  NA
 [648,]       NA       NA  NA  NA
 [649,]       NA       NA  NA  NA
 [650,]       NA       NA  NA  NA
 [651,]       NA       NA  NA  NA
 [652,]       NA       NA  NA  NA
 [653,]       NA       NA  NA  NA
 [654,]       NA       NA  NA  NA
 [655,]       NA       NA  NA  NA
 [656,]       NA       NA  NA  NA
 [657,]       NA       NA  NA  NA
 [658,]       NA       NA  NA  NA
 [659,]       NA       NA  NA  NA
 [660,]       NA       NA  NA  NA
 [661,]       NA       NA  NA  NA
 [662,]       NA       NA  NA  NA
 [663,]       NA       NA  NA  NA
 [664,]       NA       NA  NA  NA
 [665,]       NA       NA  NA  NA
 [666,]       NA       NA  NA  NA
 [667,]       NA       NA  NA  NA
 [668,]       NA       NA  NA  NA
 [669,]       NA       NA  NA  NA
 [670,]       NA       NA  NA  NA
 [671,]       NA       NA  NA  NA
 [672,]       NA       NA  NA  NA
 [673,]       NA       NA  NA  NA
 [674,]       NA       NA  NA  NA
 [675,]       NA       NA  NA  NA
 [676,]       NA       NA  NA  NA
 [677,]       NA       NA  NA  NA
 [678,]       NA       NA  NA  NA
 [679,]       NA       NA  NA  NA
 [680,]       NA       NA  NA  NA
 [681,]       NA       NA  NA  NA
 [682,]       NA       NA  NA  NA
 [683,]       NA       NA  NA  NA
 [684,]       NA       NA  NA  NA
 [685,]       NA       NA  NA  NA
 [686,]       NA       NA  NA  NA
 [687,]       NA       NA  NA  NA
 [688,]       NA       NA  NA  NA
 [689,]       NA       NA  NA  NA
 [690,]       NA       NA  NA  NA
 [691,]       NA       NA  NA  NA
 [692,]       NA       NA  NA  NA
 [693,]       NA       NA  NA  NA
 [694,]       NA       NA  NA  NA
 [695,]       NA       NA  NA  NA
 [696,]       NA       NA  NA  NA
 [697,]       NA       NA  NA  NA
 [698,]       NA       NA  NA  NA
 [699,]       NA       NA  NA  NA
 [700,]       NA       NA  NA  NA
 [701,]       NA       NA  NA  NA
 [702,]       NA       NA  NA  NA
 [703,]       NA       NA  NA  NA
 [704,]       NA       NA  NA  NA
 [705,]       NA       NA  NA  NA
 [706,]       NA       NA  NA  NA
 [707,]       NA       NA  NA  NA
 [708,]       NA       NA  NA  NA
 [709,]       NA       NA  NA  NA
 [710,]       NA       NA  NA  NA
 [711,]       NA       NA  NA  NA
 [712,]       NA       NA  NA  NA
 [713,]       NA       NA  NA  NA
 [714,]       NA       NA  NA  NA
 [715,]       NA       NA  NA  NA
 [716,]       NA       NA  NA  NA
 [717,]       NA       NA  NA  NA
 [718,]       NA       NA  NA  NA
 [719,]       NA       NA  NA  NA
 [720,]       NA       NA  NA  NA
 [721,]       NA       NA  NA  NA
 [722,]       NA       NA  NA  NA
 [723,]       NA       NA  NA  NA
 [724,]       NA       NA  NA  NA
 [725,]       NA       NA  NA  NA
 [726,]       NA       NA  NA  NA
 [727,]       NA       NA  NA  NA
 [728,]       NA       NA  NA  NA
 [729,]       NA       NA  NA  NA
 [730,]       NA       NA  NA  NA
 [731,]       NA       NA  NA  NA
 [732,]       NA       NA  NA  NA
 [733,]       NA       NA  NA  NA
 [734,]       NA       NA  NA  NA
 [735,]       NA       NA  NA  NA
 [736,]       NA       NA  NA  NA
 [737,]       NA       NA  NA  NA
 [738,]       NA       NA  NA  NA
 [739,]       NA       NA  NA  NA
 [740,]       NA       NA  NA  NA
 [741,]       NA       NA  NA  NA
 [742,]       NA       NA  NA  NA
 [743,]       NA       NA  NA  NA
 [744,]       NA       NA  NA  NA
 [745,]       NA       NA  NA  NA
 [746,]       NA       NA  NA  NA
 [747,]       NA       NA  NA  NA
 [748,]       NA       NA  NA  NA
 [749,]       NA       NA  NA  NA
 [750,]       NA       NA  NA  NA
 [751,]       NA       NA  NA  NA
 [752,]       NA       NA  NA  NA
 [753,]       NA       NA  NA  NA
 [754,]       NA       NA  NA  NA
 [755,]       NA       NA  NA  NA
 [756,]       NA       NA  NA  NA
 [757,]       NA       NA  NA  NA
 [758,]       NA       NA  NA  NA
 [759,]       NA       NA  NA  NA
 [760,]       NA       NA  NA  NA
 [761,]       NA       NA  NA  NA
 [762,]       NA       NA  NA  NA
 [763,]       NA       NA  NA  NA
 [764,]       NA       NA  NA  NA
 [765,]       NA       NA  NA  NA
 [766,]       NA       NA  NA  NA
 [767,]       NA       NA  NA  NA
 [768,]       NA       NA  NA  NA
 [769,]       NA       NA  NA  NA
 [770,]       NA       NA  NA  NA
 [771,]       NA       NA  NA  NA
 [772,]       NA       NA  NA  NA
 [773,]       NA       NA  NA  NA
 [774,]       NA       NA  NA  NA
 [775,]       NA       NA  NA  NA
 [776,]       NA       NA  NA  NA
 [777,]       NA       NA  NA  NA
 [778,]       NA       NA  NA  NA
 [779,]       NA       NA  NA  NA
 [780,]       NA       NA  NA  NA
 [781,]       NA       NA  NA  NA
 [782,]       NA       NA  NA  NA
 [783,]       NA       NA  NA  NA
 [784,]       NA       NA  NA  NA
 [785,]       NA       NA  NA  NA
 [786,]       NA       NA  NA  NA
 [787,]       NA       NA  NA  NA
 [788,]       NA       NA  NA  NA
 [789,]       NA       NA  NA  NA
 [790,]       NA       NA  NA  NA
 [791,]       NA       NA  NA  NA
 [792,]       NA       NA  NA  NA
 [793,]       NA       NA  NA  NA
 [794,]       NA       NA  NA  NA
 [795,]       NA       NA  NA  NA
 [796,]       NA       NA  NA  NA
 [797,]       NA       NA  NA  NA
 [798,]       NA       NA  NA  NA
 [799,]       NA       NA  NA  NA
 [800,]       NA       NA  NA  NA
 [801,]       NA       NA  NA  NA
 [802,]       NA       NA  NA  NA
 [803,]       NA       NA  NA  NA
 [804,]       NA       NA  NA  NA
 [805,]       NA       NA  NA  NA
 [806,]       NA       NA  NA  NA
 [807,]       NA       NA  NA  NA
 [808,]       NA       NA  NA  NA
 [809,]       NA       NA  NA  NA
 [810,]       NA       NA  NA  NA
 [811,]       NA       NA  NA  NA
 [812,]       NA       NA  NA  NA
 [813,]       NA       NA  NA  NA
 [814,]       NA       NA  NA  NA
 [815,]       NA       NA  NA  NA
 [816,]       NA       NA  NA  NA
 [817,]       NA       NA  NA  NA
 [818,]       NA       NA  NA  NA
 [819,]       NA       NA  NA  NA
 [820,]       NA       NA  NA  NA
 [821,]       NA       NA  NA  NA
 [822,]       NA       NA  NA  NA
 [823,]       NA       NA  NA  NA
 [824,]       NA       NA  NA  NA
 [825,]       NA       NA  NA  NA
 [826,]       NA       NA  NA  NA
 [827,]       NA       NA  NA  NA
 [828,]       NA       NA  NA  NA
 [829,]       NA       NA  NA  NA
 [830,]       NA       NA  NA  NA
 [831,]       NA       NA  NA  NA
 [832,]       NA       NA  NA  NA
 [833,]       NA       NA  NA  NA
 [834,]       NA       NA  NA  NA
 [835,]       NA       NA  NA  NA
 [836,]       NA       NA  NA  NA
 [837,]       NA       NA  NA  NA
 [838,]       NA       NA  NA  NA
 [839,]       NA       NA  NA  NA
 [840,]       NA       NA  NA  NA
 [841,]       NA       NA  NA  NA
 [842,]       NA       NA  NA  NA
 [843,]       NA       NA  NA  NA
 [844,]       NA       NA  NA  NA
 [845,]       NA       NA  NA  NA
 [846,]       NA       NA  NA  NA
 [847,]       NA       NA  NA  NA
 [848,]       NA       NA  NA  NA
 [849,]       NA       NA  NA  NA
 [850,]       NA       NA  NA  NA
 [851,]       NA       NA  NA  NA
 [852,]       NA       NA  NA  NA
 [853,]       NA       NA  NA  NA
 [854,]       NA       NA  NA  NA
 [855,]       NA       NA  NA  NA
 [856,]       NA       NA  NA  NA
 [857,]       NA       NA  NA  NA
 [858,]       NA       NA  NA  NA
 [859,]       NA       NA  NA  NA
 [860,]       NA       NA  NA  NA
 [861,]       NA       NA  NA  NA
 [862,]       NA       NA  NA  NA
 [863,]       NA       NA  NA  NA
 [864,]       NA       NA  NA  NA
 [865,]       NA       NA  NA  NA
 [866,]       NA       NA  NA  NA
 [867,]       NA       NA  NA  NA
 [868,]       NA       NA  NA  NA
 [869,]       NA       NA  NA  NA
 [870,]       NA       NA  NA  NA
 [871,]       NA       NA  NA  NA
 [872,]       NA       NA  NA  NA
 [873,]       NA       NA  NA  NA
 [874,]       NA       NA  NA  NA
 [875,]       NA       NA  NA  NA
 [876,]       NA       NA  NA  NA
 [877,]       NA       NA  NA  NA
 [878,]       NA       NA  NA  NA
 [879,]       NA       NA  NA  NA
 [880,]       NA       NA  NA  NA
 [881,]       NA       NA  NA  NA
 [882,]       NA       NA  NA  NA
 [883,]       NA       NA  NA  NA
 [884,]       NA       NA  NA  NA
 [885,]       NA       NA  NA  NA
 [886,]       NA       NA  NA  NA
 [887,]       NA       NA  NA  NA
 [888,]       NA       NA  NA  NA
 [889,]       NA       NA  NA  NA
 [890,]       NA       NA  NA  NA
 [891,]       NA       NA  NA  NA
 [892,]       NA       NA  NA  NA
 [893,]       NA       NA  NA  NA
 [894,]       NA       NA  NA  NA
 [895,]       NA       NA  NA  NA
 [896,]       NA       NA  NA  NA
 [897,]       NA       NA  NA  NA
 [898,]       NA       NA  NA  NA
 [899,]       NA       NA  NA  NA
 [900,]       NA       NA  NA  NA
 [901,]       NA       NA  NA  NA
 [902,]       NA       NA  NA  NA
 [903,]       NA       NA  NA  NA
 [904,]       NA       NA  NA  NA
 [905,]       NA       NA  NA  NA
 [906,]       NA       NA  NA  NA
 [907,]       NA       NA  NA  NA
 [908,]       NA       NA  NA  NA
 [909,]       NA       NA  NA  NA
 [910,]       NA       NA  NA  NA
 [911,]       NA       NA  NA  NA
 [912,]       NA       NA  NA  NA
 [913,]       NA       NA  NA  NA
 [914,]       NA       NA  NA  NA
 [915,]       NA       NA  NA  NA
 [916,]       NA       NA  NA  NA
 [917,]       NA       NA  NA  NA
 [918,]       NA       NA  NA  NA
 [919,]       NA       NA  NA  NA
 [920,]       NA       NA  NA  NA
 [921,]       NA       NA  NA  NA
 [922,]       NA       NA  NA  NA
 [923,]       NA       NA  NA  NA
 [924,]       NA       NA  NA  NA
 [925,]       NA       NA  NA  NA
 [926,]       NA       NA  NA  NA
 [927,]       NA       NA  NA  NA
 [928,]       NA       NA  NA  NA
 [929,]       NA       NA  NA  NA
 [930,]       NA       NA  NA  NA
 [931,]       NA       NA  NA  NA
 [932,]       NA       NA  NA  NA
 [933,]       NA       NA  NA  NA
 [934,]       NA       NA  NA  NA
 [935,]       NA       NA  NA  NA
 [936,]       NA       NA  NA  NA
 [937,]       NA       NA  NA  NA
 [938,]       NA       NA  NA  NA
 [939,]       NA       NA  NA  NA
 [940,]       NA       NA  NA  NA
 [941,]       NA       NA  NA  NA
 [942,]       NA       NA  NA  NA
 [943,]       NA       NA  NA  NA
 [944,]       NA       NA  NA  NA
 [945,]       NA       NA  NA  NA
 [946,]       NA       NA  NA  NA
 [947,]       NA       NA  NA  NA
 [948,]       NA       NA  NA  NA
 [949,]       NA       NA  NA  NA
 [950,]       NA       NA  NA  NA
 [951,]       NA       NA  NA  NA
 [952,]       NA       NA  NA  NA
 [953,]       NA       NA  NA  NA
 [954,]       NA       NA  NA  NA
 [955,]       NA       NA  NA  NA
 [956,]       NA       NA  NA  NA
 [957,]       NA       NA  NA  NA
 [958,]       NA       NA  NA  NA
 [959,]       NA       NA  NA  NA
 [960,]       NA       NA  NA  NA
 [961,]       NA       NA  NA  NA
 [962,]       NA       NA  NA  NA
 [963,]       NA       NA  NA  NA
 [964,]       NA       NA  NA  NA
 [965,]       NA       NA  NA  NA
 [966,]       NA       NA  NA  NA
 [967,]       NA       NA  NA  NA
 [968,]       NA       NA  NA  NA
 [969,]       NA       NA  NA  NA
 [970,]       NA       NA  NA  NA
 [971,]       NA       NA  NA  NA
 [972,]       NA       NA  NA  NA
 [973,]       NA       NA  NA  NA
 [974,]       NA       NA  NA  NA
 [975,]       NA       NA  NA  NA
 [976,]       NA       NA  NA  NA
 [977,]       NA       NA  NA  NA
 [978,]       NA       NA  NA  NA
 [979,]       NA       NA  NA  NA
 [980,]       NA       NA  NA  NA
 [981,]       NA       NA  NA  NA
 [982,]       NA       NA  NA  NA
 [983,]       NA       NA  NA  NA
 [984,]       NA       NA  NA  NA
 [985,]       NA       NA  NA  NA
 [986,]       NA       NA  NA  NA
 [987,]       NA       NA  NA  NA
 [988,]       NA       NA  NA  NA
 [989,]       NA       NA  NA  NA
 [990,]       NA       NA  NA  NA
 [991,]       NA       NA  NA  NA
 [992,]       NA       NA  NA  NA
 [993,]       NA       NA  NA  NA
 [994,]       NA       NA  NA  NA
 [995,]       NA       NA  NA  NA
 [996,]       NA       NA  NA  NA
 [997,]       NA       NA  NA  NA
 [998,]       NA       NA  NA  NA
 [999,]       NA       NA  NA  NA
[1000,]       NA       NA  NA  NA</code></pre>
</div>
</div>
<div class="absolute" style="font-size: 36px;top: 560px; left: 600px; ">
<p><blue>Store (one-step-ahead) forecast errors of:</blue></p>
</div>
<div class="absolute" style="font-size: 36px;top: 620px; left: 600px; ">
<p><code>ARIMA110</code>: ARIMA(1,1,0) model</p>
</div>
<div class="absolute" style="font-size: 36px;top: 680px; left: 600px; ">
<p><code>ARIMA200</code>: ARIMA(2,0,0) model</p>
</div>
<div class="absolute" style="font-size: 36px;top: 740px; left: 600px; ">
<p><code>ADF</code>: Model selected by ADF test</p>
</div>
<div class="absolute" style="font-size: 36px;top: 800px; left: 600px; ">
<p><code>AIC</code>: Model selected by AICc</p>
</div>
</section>
<section id="simulation-code" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Simulation Code</h2>
<p><blue>Code structure:</blue></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb10-1" class="hljs-ln-code"><a></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb10-2" class="hljs-ln-code"><a></a><span class="cf">for</span> (r <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>reps){</span>
<span id="cb10-3" class="hljs-ln-code"><a></a></span>
<span id="cb10-4" class="hljs-ln-code"><a></a>  <span class="co"># a. Generate Y</span></span>
<span id="cb10-5" class="hljs-ln-code"><a></a></span>
<span id="cb10-6" class="hljs-ln-code"><a></a>  <span class="co"># b. Estimate ARIMA(2,0,0) and ARIMA(1,1,0) models for Y</span></span>
<span id="cb10-7" class="hljs-ln-code"><a></a></span>
<span id="cb10-8" class="hljs-ln-code"><a></a>  <span class="co"># c. Compute and store 1-step-ahead forecast errors for each model</span></span>
<span id="cb10-9" class="hljs-ln-code"><a></a>  <span class="co">#    in columns 1 and 2 of ForecastErrors</span></span>
<span id="cb10-10" class="hljs-ln-code"><a></a></span>
<span id="cb10-11" class="hljs-ln-code"><a></a>  <span class="co"># d. ADF test on Y, store decision in column 1 of ur</span></span>
<span id="cb10-12" class="hljs-ln-code"><a></a>  <span class="co">#    Store forecast error of ADF-chosen model in col 3 of ForecastErrors</span></span>
<span id="cb10-13" class="hljs-ln-code"><a></a></span>
<span id="cb10-14" class="hljs-ln-code"><a></a>  <span class="co"># e. AIC choice between ARIMA(2,0,0) and ARIMA(1,1,0)</span></span>
<span id="cb10-15" class="hljs-ln-code"><a></a>  <span class="co">#    Store decision in column 2 of ur</span></span>
<span id="cb10-16" class="hljs-ln-code"><a></a>  <span class="co">#    Store forecast error of AIC-chosen model in col 4 of ForecastErrors</span></span>
<span id="cb10-17" class="hljs-ln-code"><a></a></span>
<span id="cb10-18" class="hljs-ln-code"><a></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="simulation-code-1" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Simulation Code</h2>
<p><blue><strong>Part a:</strong> Generate data from an AR(1) model: <span class="math inline">\(Y_t=\phi_{1}Y_{t-1}+U_{t}\)</span>.</blue></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a>  <span class="co"># a. Generate Y</span></span>
<span id="cb11-2"><a></a>  </span>
<span id="cb11-3"><a></a>  <span class="cf">if</span> (phi1<span class="sc">==</span><span class="dv">1</span>){</span>
<span id="cb11-4"><a></a>    Y <span class="ot">&lt;-</span> <span class="fu">arima.sim</span>(<span class="at">n=</span>n<span class="sc">+</span><span class="dv">1</span>, <span class="at">model=</span><span class="fu">list</span>(<span class="at">order=</span><span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>)))[<span class="sc">-</span><span class="dv">1</span>]</span>
<span id="cb11-5"><a></a>  } <span class="cf">else</span> {</span>
<span id="cb11-6"><a></a>    Y <span class="ot">&lt;-</span> <span class="fu">arima.sim</span>(<span class="at">n=</span>n<span class="sc">+</span><span class="dv">1</span>, <span class="at">model=</span><span class="fu">list</span>(<span class="at">ar=</span>phi1))</span>
<span id="cb11-7"><a></a>  }</span>
<span id="cb11-8"><a></a>  </span>
<span id="cb11-9"><a></a>  <span class="co"># Keep aside Y[n+1] (last element) for forecast evaluation</span></span>
<span id="cb11-10"><a></a>  Yf <span class="ot">&lt;-</span> Y[n<span class="sc">+</span><span class="dv">1</span>]</span>
<span id="cb11-11"><a></a>  <span class="co"># Use Y1,...,Yn (first n elements) as the estimation sample</span></span>
<span id="cb11-12"><a></a>  Y <span class="ot">&lt;-</span> Y[<span class="dv">1</span><span class="sc">:</span>n]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="height: 0.5em;">

</div>
<p>When <span class="math inline">\(\phi_{1}=1\)</span>, the model becomes a random walk (<code>[-1]</code> removes the first entry):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a></a>Y <span class="ot">&lt;-</span> <span class="fu">arima.sim</span>(<span class="at">n=</span>n<span class="sc">+</span><span class="dv">1</span>, <span class="at">model =</span> <span class="fu">list</span>(<span class="at">order =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>)))</span>
<span id="cb12-2"><a></a><span class="fu">print</span>(Y)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Time Series:
Start = 0 
End = 101 
Frequency = 1 
  [1]  0.00000000 -0.89831371 -0.58991727  0.12202827 -0.09603968 -0.47068443
  [7] -1.66404419 -1.38658209 -3.32626244 -2.73854626 -3.98591382 -3.64836228
 [13] -3.45159496 -3.37719967 -2.54436119 -3.41935945 -3.79658583 -4.72555407
 [19] -4.41470072 -4.58665910 -5.13281099 -5.55641553 -5.14773482 -4.06040235
 [25] -1.65606263 -3.00703791 -3.24138840 -1.76437798 -1.58587430 -1.13592489
 [31] -2.86166728 -2.93327704 -4.77465535 -4.83904991 -5.50380224 -4.35889200
 [37] -3.32606937 -3.00882861 -3.40112690 -3.57910354 -3.89909782 -4.07822962
 [43] -5.70139453 -7.20953810 -6.71282520 -5.80615317 -5.07627835 -6.15587917
 [49] -5.06986949 -4.27665767 -5.68598521 -5.20372840 -4.71914050 -5.54753242
 [55] -5.55328911 -6.38104529 -6.85462110 -7.02819437 -6.30339832 -6.84555127
 [61] -5.98427658 -6.40518148 -7.78291191 -7.97200585 -7.93411361 -6.64606891
 [67] -7.72445658 -8.44573316 -9.68440072 -8.24650793 -7.08358516 -6.30407611
 [73] -5.86760500 -6.79646058 -6.03230590 -4.71960716 -5.29380556 -4.53068494
 [79] -5.68707748 -6.85084605 -5.20739893 -5.23925842 -6.39063816 -6.27863093
 [85] -5.96002833 -5.17542018 -4.06958024 -4.71326339 -3.37721525 -3.82797187
 [91] -3.26051047 -3.15810122 -4.69392904 -4.62644396 -4.92486785 -5.16137536
 [97] -6.53580971 -6.72071775 -6.83696427 -5.97077192 -5.93077082 -5.97680673</code></pre>
</div>
</div>
</section>
<section id="simulation-code-2" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Simulation Code</h2>
<p><blue><strong>Part b:</strong> Estimate ARIMA(2,0,0) and ARIMA(1,1,0) models for <span class="math inline">\(Y_{t}\)</span></blue></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb14-1" class="hljs-ln-code"><a></a>  <span class="co"># b. Estimate ARIMA(2,0,0) and ARIMA(1,1,0) models for Y</span></span>
<span id="cb14-2" class="hljs-ln-code"><a></a></span>
<span id="cb14-3" class="hljs-ln-code"><a></a>  <span class="co"># Estimation of AR(2) model</span></span>
<span id="cb14-4" class="hljs-ln-code"><a></a>  ARIMA200 <span class="ot">&lt;-</span> <span class="fu">lm</span>(Y[t]<span class="sc">~</span>Y[t<span class="dv">-1</span>]<span class="sc">+</span>Y[t<span class="dv">-2</span>])</span>
<span id="cb14-5" class="hljs-ln-code"><a></a>  </span>
<span id="cb14-6" class="hljs-ln-code"><a></a>  <span class="co"># Estimation of ARIMA(1,1,0) model</span></span>
<span id="cb14-7" class="hljs-ln-code"><a></a>  DY <span class="ot">&lt;-</span> Y[t]<span class="sc">-</span>Y[t<span class="dv">-1</span>]</span>
<span id="cb14-8" class="hljs-ln-code"><a></a>  DY1 <span class="ot">&lt;-</span> Y[t<span class="dv">-1</span>]<span class="sc">-</span>Y[t<span class="dv">-2</span>]</span>
<span id="cb14-9" class="hljs-ln-code"><a></a>  ARIMA110 <span class="ot">&lt;-</span> <span class="fu">lm</span>(DY[t]<span class="sc">~</span>DY[t<span class="dv">-1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div title="Notes">
<div class="callout callout-tip callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Notes</strong></p>
</div>
<div class="callout-content">
<ul>
<li>Recall we set <code>t = (p+1):n</code>, and <code>p = 2</code> is the AR order.</li>
<li><blue><strong>Why do we use <code>lm</code> instead of <code>Arima</code> this time?</strong></blue>
<ul>
<li>This is because when <span class="math inline">\(\phi_{1}=1\)</span>, the series is not stationary.</li>
<li><code>Arima</code> command enforces a stationarity check and will return an error in this case.</li>
<li>Beneath the surface <code>Arima</code> is attempting to do “maximum likelihood” estimation, which can be tricky in non-stationary settings, while <code>lm</code> is doing least squares which continues to be workable.</li>
</ul></li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section id="simulation-code-3" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Simulation Code</h2>
<p><blue><strong>Part c:</strong> Compute one step ahead forecast errors</blue></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb15-1" class="hljs-ln-code"><a></a>  <span class="co"># c. Compute and store 1-step-ahead forecast errors for each model</span></span>
<span id="cb15-2" class="hljs-ln-code"><a></a>  <span class="co">#    in columns 1 and 2 of ForecastErrors</span></span>
<span id="cb15-3" class="hljs-ln-code"><a></a></span>
<span id="cb15-4" class="hljs-ln-code"><a></a>  b1 <span class="ot">&lt;-</span> ARIMA110<span class="sc">$</span>coefficients</span>
<span id="cb15-5" class="hljs-ln-code"><a></a>  ForecastErrors[r,<span class="dv">1</span>] <span class="ot">&lt;-</span> Yf <span class="sc">-</span> (Y[n]<span class="sc">+</span>b1[<span class="dv">1</span>]<span class="sc">+</span>b1[<span class="dv">2</span>]<span class="sc">*</span>DY[<span class="fu">length</span>(DY)])</span>
<span id="cb15-6" class="hljs-ln-code"><a></a></span>
<span id="cb15-7" class="hljs-ln-code"><a></a>  b2 <span class="ot">&lt;-</span> ARIMA200<span class="sc">$</span>coefficients</span>
<span id="cb15-8" class="hljs-ln-code"><a></a>  ForecastErrors[r,<span class="dv">2</span>] <span class="ot">&lt;-</span> Yf <span class="sc">-</span> (b2[<span class="dv">1</span>]<span class="sc">+</span>b2[<span class="dv">2</span>]<span class="sc">*</span>Y[n]<span class="sc">+</span>b2[<span class="dv">3</span>]<span class="sc">*</span>Y[n<span class="dv">-1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div title="Notes">
<div class="callout callout-tip callout-titled callout-style-simple">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Notes</strong></p>
</div>
<div class="callout-content">
<ul>
<li><code>Yf</code> is the actual 1-step-ahead observation (<span class="math inline">\(Y_{n+1}\)</span>)</li>
<li>Forecast errors are computed as: <span class="math display">\[\hat{U}_{n+1}=Y_{n+1}-\hat{\mathbb{E}}[Y_{n+1}\mid\mathscr{Y}_{n}]\]</span> where the forecasting equations are: <span class="math display">\[\begin{aligned}\text{ARIMA(1,1,0):}&amp;&amp; \hat{\mathbb{E}}[Y_{n+1}\mid\mathscr{Y}_{n}]&amp;=Y_{n}+\color{blue}{\widehat{\Delta Y}_{n+1}}\,\color{black}{=Y_{n}\,+}\,\color{blue}{(\hat{\beta}_{0}+\hat{\psi}_{1}\Delta Y_{n})}\\
\text{ARIMA(2,0,0):}&amp;&amp; \hat{\mathbb{E}}[Y_{n+1}\mid\mathscr{Y}_{n}]&amp;=\hat{\beta}_{0}+\hat{\phi}_{1}Y_{n}+\hat{\phi}_{2}Y_{n-1}
\end{aligned}\]</span></li>
</ul>
</div>
</div>
</div>
</div>
</section>
<section id="simulation-code-4" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Simulation Code</h2>
<p><blue><strong>Part d:</strong> Perform the ADF test to check for differencing</blue></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb16-1" class="hljs-ln-code"><a></a>  <span class="co"># d. ADF test on Y, store decision in column 1 of ur</span></span>
<span id="cb16-2" class="hljs-ln-code"><a></a></span>
<span id="cb16-3" class="hljs-ln-code"><a></a>  <span class="co"># ADF test with drift, lags=1 (include one augmenting term)</span></span>
<span id="cb16-4" class="hljs-ln-code"><a></a>  adf_tstat <span class="ot">=</span> <span class="fu">ur.df</span>(Y, <span class="at">type=</span><span class="st">"drift"</span>, <span class="at">lags=</span><span class="dv">1</span>)<span class="sc">@</span>teststat[<span class="dv">1</span>]</span>
<span id="cb16-5" class="hljs-ln-code"><a></a>  ur[r,<span class="dv">1</span>] <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">punitroot</span>(adf_tstat, <span class="at">N=</span>n, <span class="at">trend=</span><span class="st">"c"</span>, <span class="at">statistic=</span><span class="st">"t"</span>)<span class="sc">&gt;</span><span class="fl">0.05</span>)</span>
<span id="cb16-6" class="hljs-ln-code"><a></a>  </span>
<span id="cb16-7" class="hljs-ln-code"><a></a>  <span class="co"># Store forecast error of ADF-chosen model in col 3 of ForecastErrors</span></span>
<span id="cb16-8" class="hljs-ln-code"><a></a>  </span>
<span id="cb16-9" class="hljs-ln-code"><a></a>  <span class="co"># If ADF test selects unit root use ARIMA110 forecast error:</span></span>
<span id="cb16-10" class="hljs-ln-code"><a></a>  <span class="cf">if</span> (ur[r,<span class="dv">1</span>]<span class="sc">==</span><span class="dv">1</span>){</span>
<span id="cb16-11" class="hljs-ln-code"><a></a>    ForecastErrors[r,<span class="dv">3</span>] <span class="ot">&lt;-</span> ForecastErrors[r,<span class="dv">1</span>]  </span>
<span id="cb16-12" class="hljs-ln-code"><a></a>  } <span class="cf">else</span> { </span>
<span id="cb16-13" class="hljs-ln-code"><a></a>    <span class="co"># otherwise use ARIMA200 forecast error:</span></span>
<span id="cb16-14" class="hljs-ln-code"><a></a>    ForecastErrors[r,<span class="dv">3</span>] <span class="ot">&lt;-</span> ForecastErrors[r,<span class="dv">2</span>]  </span>
<span id="cb16-15" class="hljs-ln-code"><a></a>  }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="height: 0.5em;">

</div>
<p>Recall the hypotheses of the ADF test are: <span class="math display">\[\begin{align}
H_{0}:&amp;\;\varphi=0&amp; &amp;\text{($Y_{t}$ has a unit root)}\\
H_{1}:&amp;\;\varphi&lt;0&amp; &amp;\text{($Y_{t}$ does not have a unit root)}
\end{align}\]</span> thus if <span class="math inline">\(p&gt;0.05 \implies H_{0}\)</span> is maintained, ADF suggests ARIMA(1,1,0) <blue><span class="math inline">\(\to\)</span> <strong>record 1</strong></blue></p>
</section>
<section id="simulation-code-5" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Simulation Code</h2>
<p><blue><strong>Part e:</strong> Use AIC to check for differencing</blue></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb17-1" class="hljs-ln-code"><a></a>  <span class="co"># e. AIC choice between ARIMA(2,0,0) and ARIMA(1,1,0)</span></span>
<span id="cb17-2" class="hljs-ln-code"><a></a></span>
<span id="cb17-3" class="hljs-ln-code"><a></a>  <span class="co"># Store decision in column 2 of ur</span></span>
<span id="cb17-4" class="hljs-ln-code"><a></a>  ur[r,<span class="dv">2</span>] <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">*</span>(<span class="fu">AIC</span>(ARIMA110)<span class="sc">&lt;</span><span class="fu">AIC</span>(ARIMA200))</span>
<span id="cb17-5" class="hljs-ln-code"><a></a></span>
<span id="cb17-6" class="hljs-ln-code"><a></a>  <span class="co"># Store forecast error of AIC-chosen model in col 4 of ForecastErrors</span></span>
<span id="cb17-7" class="hljs-ln-code"><a></a>  <span class="cf">if</span> (ur[r,<span class="dv">2</span>]<span class="sc">==</span><span class="dv">1</span>){</span>
<span id="cb17-8" class="hljs-ln-code"><a></a>    <span class="co"># If AIC selects unit root use ARIMA110 forecast error:</span></span>
<span id="cb17-9" class="hljs-ln-code"><a></a>    ForecastErrors[r,<span class="dv">4</span>] <span class="ot">&lt;-</span> ForecastErrors[r,<span class="dv">1</span>]  </span>
<span id="cb17-10" class="hljs-ln-code"><a></a>  } <span class="cf">else</span> {</span>
<span id="cb17-11" class="hljs-ln-code"><a></a>    <span class="co"># otherwise use ARIMA200 forecast error:</span></span>
<span id="cb17-12" class="hljs-ln-code"><a></a>    ForecastErrors[r,<span class="dv">4</span>] <span class="ot">&lt;-</span> ForecastErrors[r,<span class="dv">2</span>]  </span>
<span id="cb17-13" class="hljs-ln-code"><a></a>  }</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="horizontal-line">

</div>
<p>Recall that when AIC is used, we select ARIMA(1,1,0) if <span class="math display">\[\operatorname{AIC}_{\operatorname{ARIMA(1,1,0)}}&lt;\operatorname{AIC}_{\operatorname{ARIMA(2,0,0)}}\]</span> if this is satisfied, store <code>ur[r,2]=1</code>, and store the forecast error of ARIMA(1,1,0) under <code>ForecastErrors[r,4]</code>.</p>
</section>
<section id="simulation-results" class="slide level2">
<h2>Simulation Results</h2>
<p>To make the results reproducible, we set a random seed at <code>42</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a></a><span class="fu">set.seed</span>(<span class="dv">42</span>)    </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="horizontal-line">

</div>
<p>Running the completed code produces the following results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a></a><span class="fu">head</span>(ur)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     ADF AIC
[1,]   1   1
[2,]   0   0
[3,]   1   1
[4,]   1   1
[5,]   1   1
[6,]   1   1</code></pre>
</div>
</div>
<div style="height: 0.5em;">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a></a><span class="fu">head</span>(ForecastErrors)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       ARIMA110   ARIMA200        ADF        AIC
[1,] -0.2308936 -0.4534365 -0.2308936 -0.2308936
[2,]  0.3559520 -0.2486756 -0.2486756 -0.2486756
[3,] -0.1947189 -0.4982651 -0.1947189 -0.1947189
[4,] -0.9562775 -0.6328966 -0.9562775 -0.9562775
[5,] -0.1163203  0.2310979 -0.1163203 -0.1163203
[6,] -1.2382276 -1.3633817 -1.2382276 -1.2382276</code></pre>
</div>
</div>
</section>
<section id="simulation-results-1" class="slide level2 scrollable">
<h2>Simulation Results</h2>
<div class="callout callout-note callout-style-simple">
<div class="callout-body">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-content">
<p><blue>We will compare the ADF and AIC approaches in two ways:</blue></p>
<ol type="i">
<li>proportion of “correct” choice of differencing</li>
<li>resulting one-step-ahead forecasting performance.</li>
</ol>
</div>
</div>
</div>
<div style="height: 0.25em;">

</div>
<p><strong>When <span class="math inline">\(\phi_{1}=0.9\)</span>:</strong></p>
<p><blue>Calculate the selection proportions for the ADF and AIC:</blue></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a></a><span class="co"># Selection proportions:</span></span>
<span id="cb23-2"><a></a>UnitRootSelected <span class="ot">&lt;-</span> <span class="fu">apply</span>(ur,<span class="dv">2</span>,mean)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb23-3"><a></a><span class="fu">print</span>(UnitRootSelected)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> ADF  AIC 
70.6 63.5 </code></pre>
</div>
</div>
<div style="height: 0.5em;">

</div>
<p><blue>RMSE’s of (i) always using ARIMA(1,1,0), (ii) always using ARIMA(2,0,0), (iii) choosing between them with ADF test, (iv) choosing between them with AIC:</blue></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a></a>RMSE <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">apply</span>(ForecastErrors<span class="sc">^</span><span class="dv">2</span>,<span class="dv">2</span>,mean))</span>
<span id="cb25-2"><a></a><span class="fu">print</span>(<span class="fu">round</span>(RMSE, <span class="dv">5</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>ARIMA110 ARIMA200      ADF      AIC 
 1.05121  1.02576  1.04707  1.04603 </code></pre>
</div>
</div>
</section>
<section id="simulation-looping-over-all-phi_1-values" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Simulation: Looping over all <span class="math inline">\(\phi_{1}\)</span> values</h2>
<p>Modify the code to consider all of <span class="math inline">\(\phi_{1}=1,0.95,\dots,0.5\)</span>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a></a>n <span class="ot">&lt;-</span> <span class="dv">100</span>        <span class="co"># Sample size</span></span>
<span id="cb27-2"><a></a>p <span class="ot">&lt;-</span> <span class="dv">2</span>          <span class="co"># Lag length of AR model</span></span>
<span id="cb27-3"><a></a>t <span class="ot">&lt;-</span> (p<span class="sc">+</span><span class="dv">1</span>)<span class="sc">:</span>n</span>
<span id="cb27-4"><a></a>reps <span class="ot">&lt;-</span> <span class="dv">1000</span>    <span class="co"># Number of repetitions</span></span>
<span id="cb27-5"><a></a></span>
<span id="cb27-6"><a></a><span class="co"># True value of phi1</span></span>
<span id="cb27-7"><a></a>phi1_values <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.95</span>, <span class="fl">0.9</span>, <span class="fl">0.85</span>, <span class="fl">0.8</span>, <span class="fl">0.7</span>, <span class="fl">0.6</span>, <span class="fl">0.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div style="height: 1em;">

</div>
<p>Set up two extra storage matrices for model selection results and RMSEs:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a></a><span class="co"># Stores model selection results for each phi1 (should be 8x2)</span></span>
<span id="cb28-2"><a></a>my_ur <span class="ot">=</span> <span class="fu">matrix</span>(<span class="at">nrow=</span><span class="fu">length</span>(phi1_values), <span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb28-3"><a></a><span class="fu">colnames</span>(my_ur) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ADF"</span>, <span class="st">"AIC"</span>)</span>
<span id="cb28-4"><a></a><span class="fu">rownames</span>(my_ur) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"phi1="</span>, phi1_values)</span>
<span id="cb28-5"><a></a></span>
<span id="cb28-6"><a></a><span class="co"># Stores RMSE results for each phi1 (should be 8x4)</span></span>
<span id="cb28-7"><a></a>my_RMSE <span class="ot">=</span> <span class="fu">matrix</span>(<span class="at">nrow=</span><span class="fu">length</span>(phi1_values), <span class="at">ncol=</span><span class="dv">4</span>)</span>
<span id="cb28-8"><a></a><span class="fu">colnames</span>(my_RMSE) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ARIMA110"</span>, <span class="st">"ARIMA200"</span>, <span class="st">"ADF"</span>, <span class="st">"AIC"</span>)</span>
<span id="cb28-9"><a></a><span class="fu">rownames</span>(my_RMSE) <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"phi1="</span>, phi1_values)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="simulation-looping-over-all-phi_1-values-1" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Simulation: Looping over all <span class="math inline">\(\phi_{1}\)</span> values</h2>
<p>Next, add an extra layer of <code>for</code> loop for <code>phi1</code> (<span class="math inline">\(\phi_{1}\)</span>) values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb29-1" class="hljs-ln-code"><a></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(phi1_values)){</span>
<span id="cb29-2" class="hljs-ln-code"><a></a>  </span>
<span id="cb29-3" class="hljs-ln-code"><a></a>  phi1 <span class="ot">=</span> phi1_values[i]</span>
<span id="cb29-4" class="hljs-ln-code"><a></a>  </span>
<span id="cb29-5" class="hljs-ln-code"><a></a>  ur <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">nrow=</span>reps, <span class="at">ncol=</span><span class="dv">2</span>)</span>
<span id="cb29-6" class="hljs-ln-code"><a></a>  <span class="fu">colnames</span>(ur) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ADF"</span>, <span class="st">"AIC"</span>)</span>
<span id="cb29-7" class="hljs-ln-code"><a></a>  </span>
<span id="cb29-8" class="hljs-ln-code"><a></a>  ForecastErrors <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">nrow=</span>reps, <span class="at">ncol=</span><span class="dv">4</span>)</span>
<span id="cb29-9" class="hljs-ln-code"><a></a>  <span class="fu">colnames</span>(ForecastErrors) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ARIMA110"</span>, <span class="st">"ARIMA200"</span>, <span class="st">"ADF"</span>, <span class="st">"AIC"</span>)</span>
<span id="cb29-10" class="hljs-ln-code"><a></a>  </span>
<span id="cb29-11" class="hljs-ln-code"><a></a>  <span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb29-12" class="hljs-ln-code"><a></a>  <span class="cf">for</span> (r <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>reps){</span>
<span id="cb29-13" class="hljs-ln-code"><a></a>    </span>
<span id="cb29-14" class="hljs-ln-code"><a></a>    <span class="co"># steps a-e code goes here...</span></span>
<span id="cb29-15" class="hljs-ln-code"><a></a>    </span>
<span id="cb29-16" class="hljs-ln-code"><a></a>  }</span>
<span id="cb29-17" class="hljs-ln-code"><a></a>  </span>
<span id="cb29-18" class="hljs-ln-code"><a></a>  my_ur[i,] <span class="ot">&lt;-</span> <span class="fu">apply</span>(ur, <span class="dv">2</span>, mean)<span class="sc">*</span><span class="dv">100</span></span>
<span id="cb29-19" class="hljs-ln-code"><a></a>  my_RMSE[i,] <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(<span class="fu">apply</span>(ForecastErrors<span class="sc">^</span><span class="dv">2</span>, <span class="dv">2</span>, mean))</span>
<span id="cb29-20" class="hljs-ln-code"><a></a>  </span>
<span id="cb29-21" class="hljs-ln-code"><a></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="results" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Results</h2>
<p>Running the completed code produces the following results:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a></a><span class="fu">print</span>(my_ur)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           ADF  AIC
phi1=1    95.8 93.3
phi1=0.95 89.4 84.6
phi1=0.9  70.6 63.5
phi1=0.85 44.3 37.8
phi1=0.8  20.7 19.4
phi1=0.7   2.3  3.7
phi1=0.6   0.2  0.9
phi1=0.5   0.0  0.1</code></pre>
</div>
</div>
<div style="height: 1em;">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a></a><span class="fu">print</span>(<span class="fu">round</span>(my_RMSE,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          ARIMA110 ARIMA200    ADF    AIC
phi1=1      0.9877   1.0039 0.9912 0.9904
phi1=0.95   1.0300   1.0141 1.0328 1.0304
phi1=0.9    1.0512   1.0258 1.0471 1.0460
phi1=0.85   1.0887   1.0474 1.0744 1.0721
phi1=0.8    1.0889   1.0275 1.0389 1.0458
phi1=0.7    1.1163   1.0521 1.0599 1.0575
phi1=0.6    1.0941   1.0042 1.0076 1.0108
phi1=0.5    1.1554   1.0161 1.0161 1.0164</code></pre>
</div>
</div>
</section>
<section id="results-unit-root-detection" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Results: Unit Root Detection</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb34-1" class="hljs-ln-code"><a></a><span class="fu">print</span>(<span class="fu">t</span>(my_ur))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    phi1=1 phi1=0.95 phi1=0.9 phi1=0.85 phi1=0.8 phi1=0.7 phi1=0.6 phi1=0.5
ADF   95.8      89.4     70.6      44.3     20.7      2.3      0.2      0.0
AIC   93.3      84.6     63.5      37.8     19.4      3.7      0.9      0.1</code></pre>
</div>
</div>
<div class="horizontal-line">

</div>
<ul>
<li class="fragment">In this experiment the AIC demonstrates some tendency to find a unit root in a time series a little less than the ADF test, regardless of whether or not there is a unit root.</li>
<li class="fragment">When <span class="math inline">\(\phi_{1}=1\)</span> (unit root) the ADF test finds a unit root 95.8% of the time, consistent (approximately) with the 5% significance level of the test. The AIC finds a unit root 93.3% of the time. This does not appear to be a huge difference on the surface.</li>
<li class="fragment">When <span class="math inline">\(\phi_{1}&lt;1\)</span> the difference between the ADF and AIC selection proportions becomes as high as about 7%. A noticeable but not huge difference. The implications of this difference are explored using forecast performance.</li>
<li class="fragment"><blue>Conclusion:</blue> Overall the AIC provides a reasonable way to distinguish between unit root or not in this experiment.</li>
</ul>
</section>
<section id="results-rmse" class="slide level2" data-auto-animate="true">
<h2 data-id="quarto-animate-title">Results: RMSE</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy" data-id="quarto-animate-code"><code class="sourceCode r hljs"><span id="cb36-1" class="hljs-ln-code"><a></a><span class="fu">print</span>(<span class="fu">round</span>(my_RMSE,<span class="dv">4</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          ARIMA110 ARIMA200    ADF    AIC
phi1=1      0.9877   1.0039 0.9912 0.9904
phi1=0.95   1.0300   1.0141 1.0328 1.0304
phi1=0.9    1.0512   1.0258 1.0471 1.0460
phi1=0.85   1.0887   1.0474 1.0744 1.0721
phi1=0.8    1.0889   1.0275 1.0389 1.0458
phi1=0.7    1.1163   1.0521 1.0599 1.0575
phi1=0.6    1.0941   1.0042 1.0076 1.0108
phi1=0.5    1.1554   1.0161 1.0161 1.0164</code></pre>
</div>
</div>
<div class="horizontal-line">

</div>
<ul>
<li class="fragment"><p>Many of the RMSEs are approximately the same. The biggest differences occur when is away from 1, i.e.&nbsp;<span class="math inline">\(\phi_{1}=0.5,0.6\)</span>.</p>
<ul>
<li class="fragment">In this case the ARIMA(1,1,0) model is clearly misspecified, and its forecasting performance suffers.</li>
<li class="fragment">However both ADF and AIC do a good job in selecting the correct model here.</li>
</ul></li>
<li class="fragment"><p>When <span class="math inline">\(\phi_{1}=1\)</span> the RMSEs are all roughly the same. This is interesting - if there is a unit root then it doesn’t matter what we do, at least for one-step-ahead forecasting.</p></li>
<li class="fragment"><p><blue>Overall the RMSEs for the ADF and AIC methods are practically the same.</blue> There is no benefit in making this decision in this experiment in using the specialised ADF, we could just as easily have used the AIC.</p></li>
<li class="fragment"><p>Maybe interestingly, there is a “grey area’ around <span class="math inline">\(\phi_{1}=0.95\)</span> to <span class="math inline">\(\phi_{1}=0.85\)</span>, where the selected models do worse than the ARIMA(2,0,0), although the RMSE differences are small.</p></li>
</ul>
</section>
<section id="final-note" class="slide level2">
<h2>Final Note</h2>
<ul>
<li class="fragment"><p>The most important thing is to understand the simulation approach.</p></li>
<li class="fragment"><p>We are using simulation to replicate the frequentist statistical concept of a sampling distribution and hence to obtain experimental evidence on the performance of some tests and forecasts.</p></li>
<li class="fragment"><p><blue>Limitation: </blue>We have only tried a limited range of data generating processes and models and so the current results are only specific to that setting.</p></li>
</ul>
</section>
<section id="section" class="slide level2" data-background-color="#000F46">
<h2></h2>
<div style="height: 85vh; display: flex; align-items: center; justify-content: center; color: white; font-size: 2em;">
<p>Thank you for coming!</p>
</div>
<script>
document.querySelectorAll("myimage").forEach(el => {
  const src = el.getAttribute("src");
  const width = el.getAttribute("width") || "100%";

  const img = document.createElement("img");
  img.src = src;
  img.style.width = width;
  img.style.maxWidth = "100%";  // prevent overflow
  el.style.display = "block";
  el.style.textAlign = "center";
  
  el.appendChild(img);
});
</script>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">
<p>Access Slides: <code>pengyunc.github.io/TSAF_Week7</code></p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1300,

        height: 950,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
            const codeEl = trigger.previousElementSibling.cloneNode(true);
            for (const childEl of codeEl.children) {
              if (isCodeAnnotation(childEl)) {
                childEl.remove();
              }
            }
            return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/pengyunc\.github\.io\/TSAF_Week7\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>